### ISSUE TITLE
In launcher mod list, show Minecraft version

### ISSUE THREAD

**Issue by mk-pmb** [MultiMC/Launcher#5176] opened 2023-06-09 11:32 UTC
### Role

I play modded Minecraft.

### Suggestion

The mod list shall offer a column for the Minecraft version (range) supported by the mod file I just added.

### Benefit

I can have easy reassurance that I picked the correct file, especially when the mod happens to be at a version is slightly below my instance's Minecraft version.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The current "Version" column should then be renamed to "Mod version".

**Comment by phit** [comment] 2023-06-11 18:32
Duplicate of https://github.com/MultiMC/Launcher/issues/3858

**Closed as completed by phit** 2023-06-11 18:32 UTC
