### ISSUE TITLE
Cannot switch accounts in account switcher on 0.6.13-develop-2880

### ISSUE THREAD

**Issue by Nyny2121** [MultiMC/Launcher#4273] opened 2021-11-22 02:47 UTC
### Operating System

Windows

### Description of bug

Bug with Account Selection

### Steps to reproduce

* I have 3 mojang accounts loaded in my account switcher
* I select the account switcher and select the first account, but it stays on the third account in the list
* I open the accounts menu, and set the first account as default, but it switches it to the third account
* I try to launch any instance after telling the switcher to switch accounts but it only uses my third account

### Suspected cause

I am running on Multimc 5 - Version 0.6.13-develop-2880 on win32

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by theofficialgman** [comment] 2021-11-22 03:13
duplicate of https://github.com/MultiMC/Launcher/issues/4265
see this issue for a workaround ^

**Closed** 2021-11-22 13:44 UTC
Labels: bug
