### ISSUE TITLE
Incorrect version downloaded for Modrinth modpack

### ISSUE THREAD

**Issue by itsmemac** [MultiMC/Launcher#4761] opened 2022-06-10 03:11 UTC
### Operating System

Windows

### Description of bug

When a modpack has multiple version and you select and try to download different version from the default one
MultiMC will still download the default modpack version

Example
Tried downloading Better MC from modrinth which has 3 versions listed in the dropdown
v10 being the default version, if you switch to v10.5 or v56 and try downloading, MultiMC will still download v10

Was able to reproduce the same issue for other people in discord as well

### Steps to reproduce

1. Click "Add instance"
2. Select "Modrinth"
3. Select "Better Minecraft"
4. Select v10.5 from dropdown and click "OK"
5. v10 will be downloaded

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Images
**Selecting modpack version**
![image](https://user-images.githubusercontent.com/37410297/172983206-24037c44-63e5-46c3-ae3b-3288726be8de.png)

**Incorrect version added**
![image](https://user-images.githubusercontent.com/37410297/172983260-2787313a-cb40-4210-9900-37d24041b611.png)

**In-game confirmation of incorrect version downloaded (ignore the forge on launcher and fabric on server. This screenshot is just to show version number)**
![image](https://user-images.githubusercontent.com/37410297/172983480-108072d8-0ff6-4b56-b396-8fddd329720b.png)

**Comment by phit** [comment] 2022-06-10 07:33
Duplicate of https://github.com/MultiMC/Launcher/issues/4724

**Closed by phit** 2022-06-10 07:33 UTC
Labels: bug
