### ISSUE TITLE
Installing fabric loader should offer to also install fabric-api and fabric-renderer-api.

### ISSUE THREAD

**Issue by mk-pmb** [MultiMC/Launcher#5188] opened 2023-06-14 00:27 UTC
### Role

I  play modded Minecraft.

### Suggestion

MultiMC's "Install fabric" version selection screen should offer an easy way to also install [fabric-api and fabric-renderer-api](https://github.com/FabricMC/fabric/releases). Installing them should be the default, and there should be an explanation that the [Fabric install guide](https://fabricmc.net/wiki/player:tutorials:install_multimc:windows) says I need them.

### Benefit

Better UX, less potential for human user making mistakes.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment] 2023-06-14 07:07
Duplicate of https://github.com/MultiMC/Launcher/issues/3055

**Closed as completed by phit** 2023-06-14 07:07 UTC
Labels: close:duplicate
