### ISSUE TITLE
ARM64 native

### ISSUE THREAD

**Issue by iMonZ** [MultiMC/Launcher#5275] opened 2023-10-10 12:57 UTC
### Operating System

macOS

### Description of bug

On macOS, the Launcher isn't using arm64.
Why don't add it? Isn't probably that hard, I could even see if I can get it working.

### Steps to reproduce

-

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by iMonZ** [comment] 2023-10-10 12:58
Especially since Apple could remove x86 support for good soon. And this launcher wants to be long term right?

**Comment by phit** [comment] 2023-10-10 16:55
Please use the search, duplicate of https://github.com/MultiMC/Launcher/issues/5075 and countless others

**Closed as completed by phit** 2023-10-10 16:55 UTC
Labels: bug

**Comment by 1oglop1** [comment] 2023-10-21 07:59
@phit Maybe pinning #5075 to give it more visibility could prevent issue creation.
Perhaps rewording the issue title to give it right away.

e.g. update title to: `Native arm64(Apple Silicon) not supported` or `Support native arm64(Apple Silicon)`

**Comment by phit** [comment] 2023-10-21 09:06
I would, but I don't have permissions to do so.

**Comment by 1oglop1** [comment] 2023-10-23 06:11
I see, I tried to avoid pinging @peterix because I am not sure who else may have the permission.
