### ISSUE TITLE
Qt5XML requirement should be mentioned on website

### ISSUE THREAD

**Issue by Erufailon4** [MultiMC/Launcher#5363] opened 2024-03-10 11:40 UTC
### Role

I'm an user of MultiMC on Linux Mint 21.3.

### Suggestion

The Linux setup binary (from "binary tarball (64-bit)" download option) depends on libqt5xml5 on Mint and presumably other Debian/Ubuntu-based systems and will not start without it installed - and it is not installed by default on Linux Mint 21.3 at least - but this is not mentioned on the website which only lists the core, network and GUI libraries of Qt 5 as requirements. libqt5xml5 should be added to the required package list on the website.

### Benefit

Mint in particular is a beginner-oriented distro, so users will expect the software to work as easily as possible and will be confused if the setup binary does not start after double-clicking it, which happens if libqt5xml5 is missing. Finding out what exactly needs to be installed to fix the problem requires trying to run the binary via the command line to see the error message. Mentioning the requirement upfront on the website would save a lot of user time and confusion.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment] 2024-03-10 11:55
Duplicate of https://github.com/MultiMC/Launcher/issues/4793

**Closed as completed by phit** 2024-03-10 11:55 UTC
