### ISSUE TITLE
Export mod list to plaintext

### ISSUE THREAD

**Issue by AlurienFlame** [MultiMC/Launcher#4591] opened 2022-03-19 22:09 UTC
### Role

I switch computers a lot, making keeping track of my prefered mod list difficult. I use a python script to write a list of my mods to a markdown table right now, but I'd love to see a feature like that built in.

### Suggestion

It would be nice if there was a button on the loader mods screen of the edit instance window that exported a list of the mods in that instance to a text file (or markdown or similar small and portable format)

### Benefit

I'd like to be able to easily save a list of my mods in a format small enough to toss into cloud storage while I switch PCs. I know I could just copy the whole instance but that takes up a lot of space.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment] 2022-03-20 10:16
Duplicate of https://github.com/MultiMC/Launcher/issues/4150

**Closed by phit** 2022-03-20 10:16 UTC
