### ISSUE TITLE
Proxy option "force offline"

### ISSUE THREAD

**Issue by mk-pmb** [MultiMC/Launcher#5274] opened 2023-10-09 18:11 UTC
### Role

I'm worried about bad advice.

### Suggestion

We should provide an explicit "force offline" proxy option to pre-empt the possible bad advice of using a "random" bogus proxy. Such advice has occurred here in issues and may occur in many other places in the future.

### Benefit

Better security for users.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

A popular example of a restricted network that requires the bogus proxy trick is a school network. Those are often especially prone to pranks; other networks may have more financially motivated attackers. When the bogus name happens to be valid enough to trigger a name resolution attempt, an attacker might capture and redirect that. They can then learn that it is a proxy request, and from some of the URLs requested they may even learn which versions of Java, MC and/or mods are being used. They can then use that to serve malicious files.

We shouldn't trust random ports on localhost either, because in some circumstances (like shared school project) it might be easy to convince someone to run software that proxies or hosts HTTP on localhost. A lot of beginner web programming projects base their security model entirely on "we're only listening on localhost so we don't need to care about attacks from outside".

If we have to provide a hostname, we should use something like `proxy`[`.invalid`](https://en.wikipedia.org/wiki/.invalid), a TLD defined specifically for hosts that are meant to be unreachable.
It's unlikely though that this knowledge will spread enough to prevent bad advice, so we should instead make it trivial for users to express their actual intent: Using a proxy setting that will force MultiMC into offline mode.

**Comment by phit** [comment] 2023-10-09 18:17
Duplicate of https://github.com/MultiMC/Launcher/issues/5078

multimc isn't some kind of security software, if you can't trust a network, dont use software on it that will make arbritrary requests

**Closed as completed by phit** 2023-10-09 18:17 UTC

**Comment by mk-pmb** [comment] 2023-10-09 19:32
I wouldn't call the other issue a dupe but rather a prime example of incomplete advice. Given our target audience I don't think we shoud expect them to know about the `.invalid` TLD.

> multimc isn't some kind of security software,

I never expected it to be. But when "use invalid proxy" is *official* advice even (as in your example thread), I think it's worth going the extra step of adding an additional radio button that matches the user's actual intent. Not being a security software means we can implement it as a low-hanging fruit like using HTTP proxy http://proxy.invalid:80/ ; the huge benefit is that if our community discovers a flaw with that approach and comes up with a better proxy setting, we roll it out accross all the user base, rather than requiring each user individually to stay informed about what the best values for "invalid proxy setting" would be.

I assume that adding the radio box would be almost trivial for someone already familiar with the code base. In that case we can help lots of people with few effort. I can try and make the patch myself if effort is the obstacle.
