### ISSUE TITLE
Mojang accounts experiencing issues when offline for too long

### ISSUE THREAD

**Issue by debwoink** [MultiMC/Launcher#4390] opened 2021-12-27 05:55 UTC
### Operating System

Windows

### Description of bug

Mojang accounts are timing out and requiring a full removal and re-add of Mojang credentials to play offline SP instead of allowing unlimited offline/no-internet offline SP as older versions of both MultiMC and the Mojang Launcher allow.

### Steps to reproduce

Wait 24-48 hours
Attempt to launch a game offline - will not launch, pops error "The account has expired and needs to be logged into manually again"
Attempt to launch a game online - same as above
Attempt to refresh credentials - status goes from "Expired" to "working" and near-instantly returns to "Expired"
Remove account and re-add via Mojang credentials
Account will now work for another 24-48 hours.

### Suspected cause

Chunks from error log:
```
    2.290 W QCoreApplication::postEvent: Unexpected null receiver
    2.290 D Task "LaunchController(0x6754db0)" starting for the first time
    3.893 C Task "LaunchController(0x6754db0)" failed:  "The account has expired and needs to be logged into manually again."
    3.893 W QCoreApplication::postEvent: Unexpected null receiver
  346.067 W QCoreApplication::postEvent: Unexpected null receiver
  346.068 D Task "LaunchController(0x67544b0)" starting for the first time
  384.062 C Task "LaunchController(0x67544b0)" failed:  "The account has expired and needs to be logged into manually again."
  384.062 W QCoreApplication::postEvent: Unexpected null receiver
 1303.810 W QCoreApplication::postEvent: Unexpected null receiver
 1303.810 D Task "LaunchController(0x67544b0)" starting for the first time
 1304.737 C Task "LaunchController(0x67544b0)" failed:  "The account has expired and needs to be logged into manually again."
 1304.737 W QCoreApplication::postEvent: Unexpected null receiver
```
 
 
 Sterile account.json w/o expiration element:
```
{
    "accounts": [
        {
            "active": true,
            "canMigrateToMSA": true,
            "profile": {
                "capes": [
                ],
                "id": "",
                "name": "",
                "skin": {
                    "data": "",
                    "id": "",
                    "url": "",
                    "variant": "CLASSIC"
                }
            },
            "type": "Mojang",
            "ygg": {
                "extra": {
                    "clientToken": "",
                    "userName": ""
                },
                "iat": 1640578529,
                "token": ""
            }
        }
    ],
    "formatVersion": 3
}
```

Potential change responsible:
https://github.com/MultiMC/Launcher/blob/d37003b1de68a74fc1dbe83128faae76f15e03d2/launcher/minecraft/auth/MinecraftAccount.cpp#L211

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by peterix** [comment] 2021-12-27 17:02
This looks like an expired account, and that's about it.

Are you copying your accounts file to multiple machines?

What exactly do you mean by offline?

**Comment by debwoink** [comment] 2021-12-31 18:09
I'm not copying my account to other devices, or doing anything with files in the MultiMC directory at all. By offline I mean using the "launch offline" option in MultiMC.

**Comment by supertin** [comment] 2022-01-11 10:00
I just opened MultiMC after a few months of not playing, updated MultiMC and got this error too... I was confused about how I'm meant to fix it. I'm sure in older versions you just got prompted to enter your password again and away you went.

I didn't want to go and delete my account profile, so I tried re-adding the same account without deleting it. MultiMC seemed OK with this, and changed the existing account in the list to "online".
If this is the correct way to fix it, could you change the error to explain this? Or bring back the old password prompt instead?

**Comment by ejm554** [comment] 2022-01-21 15:23
I'm having a similar issue. (I'm not sure it's the same as reported in this thread, so please  let me know if I should post it as a new issue.)

My Mojang accounts regularly "expire," even if I've used them less than 24 hours ago. The following screenshot shows an example of what I saw in my MultiMC GUI this morning, even though I used the account last night. 

![Screenshot 2022-01-21-090005](https://user-images.githubusercontent.com/26723535/150552004-b0e8e916-a205-4586-9ac0-7348328d481e.png)

To get an expired account working again, I'm forced to click Remove, and then Add Mojang. It would be nice if the Refresh button prompted me to re-enter the password or something, but I guess that is a separate feature request, :-)

**Comment by Heath123** [comment] 2022-01-28 09:12
I see this is marked as "needs-repro" - I can reproduce this consistently by trying to connect on my school network, which blocks the Mojang auth servers. MultiMC tries to connect multiple times then marks the account as expired, at which point I can't play offline again. I'll upload a video to demonstrate

**Comment by Heath123** [comment] 2022-01-28 09:18
Here is a video:
https://youtu.be/kfdnclRS1eo

**Comment by joernott** [comment] 2022-01-30 15:02
I actually managed to get it back to "online" by just deleting the account and re-adding it.

**Comment by ejm554** [comment] 2022-01-30 15:44
> I actually managed to get it back to "online" by just deleting the account and re-adding it.

Me too. But I hope we agree that can be annoying, especially when you have to do it frequently. One of our Mojang accounts recently started expiring every day. I'm not clear if this is a MultiMC bug or something else. Can anyone shed light on why accounts expire?

**Comment by Veyrdite** [comment] 2022-02-10 00:27
Tried MultiMC today (after many months of not using it or playing Minecraft).  Account was listed as Expired and would not refresh.

Account type was "Legacy".  Re-adding it (without deleting it) using the "Add Mojang" button replaced with with a Type "Mojang" account.  It now works again (Status: "Online").

**Comment by Kerrghan** [comment] 2022-02-10 11:34
I am getting a similar issue, I have to relog every day. For me it's with microsoft account, on top of that it has trouble reconnecting to microsoft for some reason, while microsoft says I'm logged in and MultiMC is allowed to use my account, MultiMc just gives an error (not really a related issue I think but I'm trying to fix that by using the dev updates)...

**Comment by NiceCraftz** [comment] 2022-02-10 14:09
Same issue here, its annoying af 
![image](https://user-images.githubusercontent.com/47219477/153424426-f2e5cf2a-7c7e-440b-8542-1bd400de9183.png)

**Comment by Heath123** [comment] 2022-02-10 16:11
I fixed this for myself with some code tweaks but it's not really clean enough to PR because it duplicates code, I can post it anyway though

**Comment by Heath123** [comment] 2022-02-10 16:15
This was done on PolyMC (as that was easier and doesn't make me have no branding if I need to make custom patches like this) and not tested on MultiMC, but it should work here too.
At https://github.com/MultiMC/Launcher/blob/develop/launcher/LaunchController.cpp#L213:
```diff
             case AccountState::Expired: {
-                auto errorString = tr("The account has expired and needs to be logged into manually again.");
-                QMessageBox::warning(
-                    m_parentWidget,
-                    tr("Account refresh failed"),
-                    errorString,
-                    QMessageBox::StandardButton::Ok,
-                    QMessageBox::StandardButton::Ok
-                );
-                emitFailed(errorString);
-                return;
+                if (m_session->wants_online)
+                {
+                    auto errorString = tr("The account has expired and needs to be logged into manually again.");
+                    QMessageBox::warning(
+                        m_parentWidget,
+                        tr("Account refresh failed"),
+                        errorString,
+                        QMessageBox::StandardButton::Ok,
+                        QMessageBox::StandardButton::Ok
+                    );
+                    emitFailed(errorString);
+                    return;
+                } else {
+                    // we ask the user for a player name
+                    bool ok = false;
+                    QString usedname = m_session->player_name;
+                    QString name = QInputDialog::getText(
+                        m_parentWidget,
+                        tr("Player name"),
+                        tr("Choose your offline mode player name."),
+                        QLineEdit::Normal,
+                        m_session->player_name,
+                        &ok
+                    );
+                    if (!ok)
+                    {
+                        tryagain = false;
+                        break;
+                    }
+                    if (name.length())
+                    {
+                        usedname = name;
+                    }
+                    m_session->MakeOffline(usedname);
+                    if(m_accountToUse->ownsMinecraft()) {
+                        if(!m_accountToUse->hasProfile()) {
+                            // Now handle setting up a profile name here...
+                            ProfileSetupDialog dialog(m_accountToUse, m_parentWidget);
+                            if (dialog.exec() == QDialog::Accepted)
+                            {
+                                tryagain = true;
+                                continue;
+                            }
+                            else
+                            {
+                                emitFailed(tr("Received undetermined session status during login."));
+                                return;
+                            }
+                        }
+                        // we own Minecraft, there is a profile, it's all ready to go!
+                        launchInstance();
+                        return;
+                    }
+                    else {
+                        // play demo ?
+                        QMessageBox box(m_parentWidget);
+                        box.setWindowTitle(tr("Play demo?"));
+                        box.setText(tr("This account does not own Minecraft.\nYou need to purchase the game first to play it.\n\nDo you want to play the demo?"));
+                        box.setIcon(QMessageBox::Warning);
+                        auto demoButton = box.addButton(tr("Play Demo"), QMessageBox::ButtonRole::YesRole);
+                        auto cancelButton = box.addButton(tr("Cancel"), QMessageBox::ButtonRole::NoRole);
+                        box.setDefaultButton(cancelButton);
+
+                        box.exec();
+                        if(box.clickedButton() == demoButton) {
+                            // play demo here
+                            m_session->MakeDemo();
+                            launchInstance();
+                        }
+                        else {
+                            emitFailed(tr("Launch cancelled - account does not own Minecraft."));
+                        }
+                    }
+                }
             }
             case AccountState::Gone: {
                 auto errorString = tr("The account no longer exists on the servers. It may have been migrated, in which case please add the new account you migrated this one to.");
```
I need to properly understand how this loop works so I can do it without duplicating code

**Comment by Heath123** [comment] 2022-02-10 16:16
This only works for launching in offline mode, it doesn't refresh the account

**Comment by Heath123** [comment] 2022-02-11 09:11
The code in question was a patch that I wrote, it was not copied from PolyMC, I just meant that I only tested it there

**Comment by peterix** [comment] 2022-02-14 11:51
Well, in any case, Mojang login will be getting removed from the launcher.
> Starting on 10 March 2022, your Mojang account, which is used to play Minecraft: Java Edition, must be migrated to a Microsoft account to continue playing. Don't worry – everything about your game and how you play will remain the same, including your in-game username, progress, creations and skins. The only change is how you'll log in. Plus, we'll give you a special cape just for migrating!

We're a month away from that.

**Comment by Heath123** [comment] 2022-02-14 13:25
This happens for me with Microsoft accounts, I didn't see the title

**Comment by supertin** [comment] 2022-02-17 12:18
Same thing is happening with MS accounts. Mine came up expired last night. Only converted it yesterday.

**Comment by peterix** [comment] 2022-08-12 11:35
Closing for inactivity.

**Closed** 2022-08-12 11:36 UTC
Labels: needs-repro, Auth

**Comment by Heath123** [comment] 2022-08-13 13:14
The issue is not fixed, as far as I am aware
