### ISSUE TITLE
Direwolf20 1.20 pack error

### ISSUE THREAD

**Issue by lukenator115** [MultiMC/Launcher#5292] opened 2023-11-11 21:28 UTC
### Description of bug

Couldn't create the 'server-resource-packs' folder
Instance update failed because: Component metadata update task failed while downloading from remote server:
Job 'Download of meta file net.minecraftforge/47.1.76.json' failed to process:
https://meta.multimc.org/v1/net.minecraftforge/47.1.76.json

This error displays when launching a fresh install of the direwolf20 1.20 pack, freshly imported from FTB. I found no help anywhere online.

### Steps to reproduce

Install Direwolf20 1.20 pack and run it

### Suspected cause

Hosting issue??

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by RenoFischa** [comment] 2023-11-21 23:00
MultiMC doesn't support NeoForge yet. You can change forge version to "47.1.7" in the mmc-pack.json file inside the instance folder to use it with forge.

**Comment by FeedTheChunk** [comment] 2023-11-22 00:29
Can't you just install forge from MultiMC's Edit Instance -> Version screen?

**Comment by phit** [comment] 2023-11-29 11:41
Duplicate of https://github.com/MultiMC/Launcher/issues/5232

**Closed as completed by phit** 2023-11-29 11:41 UTC
Labels: bug
