### ISSUE TITLE
Launching offline still attempts to log into Xbox

### ISSUE THREAD

**Issue by rwqfsfasxc100** [MultiMC/Launcher#5388] opened 2024-04-15 16:49 UTC
### Operating System

Other

### Description of bug

I attempted to launch the game offline (a 1.20.4 fabric instance), as at the time I was on a network that blocks gaming sites (xbox live included), and redirects to an external site explaining why the block. I figured that given it launched offline, it would prevent checks to Microsoft as I already had a functioning Microsoft account bound already, as I had booted the game the night before fine on a different network, yet when I tried launching offline, it showed the window that signifies logging into Microsoft, and due to not having access to xbox.com, it failed and asked me to log in again. I logged in using data again, and tried launching normally, and it did the same thing using the normal launch, so I believe it still tries to confirm the account's legitimacy regardless.  Due to the fact that I'm running it from the borealis VM part of chromeos, I believe that VM always has a virtual connection regardless, as I did try turning the wifi off before attempting another launch.

### Steps to reproduce

- Get a MultiMC instance to ChromeOS' borealis vm
- setup and login to your account normally
- close multimc and connect to a network with a filter that directs blocked links to a separate website, and have xbox.com blocked
- relaunch multimc and attempt to launch offline

### Suspected cause

Logging in doesn't check whether the login website(s) can be properly accessed before determining how it should boot, and launch offline will check for the account's validity regardless of a proper connection.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment] 2024-04-15 16:54
Duplicate of https://github.com/MultiMC/Launcher/issues/5078

**Closed as completed by phit** 2024-04-15 16:54 UTC
Labels: bug
