### ISSUE TITLE
No modpacks from curse forge available 

### ISSUE THREAD

**Issue by ZeroKun265** [MultiMC/Launcher#4695] opened 2022-05-18 10:03 UTC
### Operating System

Linux

### Description of bug

I tried to add a modpack i found on curseforge but when i go to add the instance, the curse forge tab has no modpacks, tried to search but still nothing, i'm running the latest version (MultiMC 0.6.15) on Arch Linux, every other search service works except for curseforge

### Steps to reproduce

Try to add a curseforge modpack

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by r18duarte** [comment] 2022-05-18 11:43
**Operating System**
Windows 10

Same issue here, same description and steps to reproduce

**Comment by gabrielkiss** [comment] 2022-05-18 11:55
I have the same issue, this is the output on my console
```
   26.547 D Downloading  "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"
   26.928 C Failed  "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"  with reason  201
   26.929 D Download failed in previous step: "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"
   26.929 D Downloading  "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"
   27.044 C Failed  "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"  with reason  201
   27.045 D Download failed in previous step: "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"
   27.045 D Downloading  "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"
   27.159 C Failed  "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"  with reason  201
   27.160 D Download failed in previous step: "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"
   27.160 D Downloading  "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"
   27.276 C Failed  "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"  with reason  201
   27.277 D Download failed in previous step: "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"
   27.277 C Task "NetJob(Flame::Search)" failed:  "Job 'Flame::Search' failed to process:
https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"
```

**Comment by ZeroKun265** [comment] 2022-05-18 12:09
I'm not great at C/C++ and i never used Qt BUT i found this on the docs

QNetworkReply::ContentAccessDenied | 201 | the access to the remote content was denied (similar to HTTP error 403)

So something to do with permissions, maybe som api changes or an expired api key? couldn't find the piece of code that does the actual requesting and downloading tho

**Comment by gabrielkiss** [comment] 2022-05-18 12:17
> So something to do with permissions

It can also mean that curseforge servers are having some problems because when quering those urls it returned 403 error

**Comment by arcomador** [comment] 2022-05-18 12:28
Curseforge has changed their API. After the transition of ownership to Overwolf, they announced they would be changing their api from an open one to one that requires api keys. Some of the code for accessing curseforge servers may need to be updated or rewritten to account for this. Users may be required to get their own API key due to limitations per key.

**Comment by phit** [comment] 2022-05-18 12:52
Update your MultiMC this is already fixed in the latest development version

**Closed by phit** 2022-05-18 12:52 UTC
Labels: bug

**Comment by glektarssza** [comment] 2022-05-18 17:52
> Update your MultiMC this is already fixed in the latest development version
> 
> @ZeroKun265 on Arch make sure to use https://github.com/MultiMC/multimc-pkgbuild

When will this fix go out onto stable?

**Comment by ZeroKun265** [comment] 2022-05-18 19:08
I'm sorry, where can i download the latest developement version? i tried using the pkgbuild but it gave me the version i had before

**Comment by RobertLSnead** [comment] 2022-05-21 18:12
After some serious research, the projectID is no longer available to the current api to retrieve the projectname to download the files. There is a way to file for the api and they do plan support latter for 3rd party down the road.  Also the file can still be retrieved if you know the location, found a bug on curseforge that would allow you to download the files with the modID and not require the projectID at all, or at least until they patch the bug.  I would be interested in the original source for the multiMC project prior to the removal of the CurseForge project.  Maybe there can be support through MMC for curseforge with some help...

**Comment by progheal** [comment] 2022-05-21 20:29
> and they do plan support latter for 3rd party down the road

@RobertLSnead Can we have the source of this? (I'd like to ask for official source if possible) Since:
a) In all these discussions here (includes the commit and this thread) no one mentioned such plan exists, until your comment;
b) The wording of the commit message of support removal looks like to me that this removal is requested by the company, without future plans.
To me this looks like the company **decides to shut down** third party support, and they do this by changing the API so third-party applications **break without mitigation**; they even go way out to these third-parties to ask for removal, which I don't think implies that there will be new third-party support.

**Comment by RobertLSnead** [comment] 2022-05-21 23:23
> > and they do plan support latter for 3rd party down the road
> 
> @RobertLSnead Can we have the source of this? (I'd like to ask for official source if possible) Since: a) In all these discussions here (includes the commit and this thread) no one mentioned such plan exists, until your comment; b) The wording of the commit message of support removal looks like to me that this removal is requested by the company, without future plans. To me this looks like the company **decides to shut down** third party support, and they do this by changing the API so third-party applications **break without mitigation**; they even go way out to these third-parties to ask for removal, which I don't think implies that there will be new third-party support.

From what I have gathered, there are some terms to which 3rd party must abide by, to what extent without reading it myself I do not know.  I do know that the current setup for the app would not suffice.  Please check out the below and read at your leisure.

Here is some references:
https://support.curseforge.com/en/support/solutions/articles/9000208346-about-the-curseforge-api-and-how-to-apply-for-a-key#key

https://docs.curseforge.com/#an-introduction-to-curseforge

**Comment by RobertLSnead** [comment] 2022-05-21 23:27
There has also been alot of talk about 3rd party.
See news here:
https://curseforge-ideas.overwolf.com/

**Comment by progheal** [comment] 2022-05-22 06:50
If that's the case, the question now is: Do the devs know of this option (API key application) but decided to not apply? Or did the devs not aware of this option until recently?
If it's the latter, I would blame Overwolf to not push hard enough by actively contact well-known users of the curse API; if it's the former, it then comes down to what's the reason of it and what can Overwolf do to "attract" old API users to accept their terms.

**Comment by glektarssza** [comment] 2022-05-23 02:11
> If that's the case, the question now is: Do the devs know of this option (API key application) but decided to not apply? Or did the devs not aware of this option until recently? If it's the latter, I would blame Overwolf to not push hard enough by actively contact well-known users of the curse API; if it's the former, it then comes down to what's the reason of it and what can Overwolf do to "attract" old API users to accept their terms.

OverWolf appears to be actively contacting the developers of 3rd party tools and requesting that they remove support for CurseForge from their applications. See 0a827ba70e6ef20187f8507a536d54a8441020dc and [this issue comment on PolyMC](https://github.com/PolyMC/PolyMC/issues/593#issuecomment-1133968518). So I think they know what they're doing and are doing it very purposefully at this point.

**Comment by RobertLSnead** [comment] 2022-05-24 15:14
Not sure why the trouble?
There is now officially 3rd party support, there are terms to respect the mod authors, ATLauncher has a working solution for that in progress.

Admins from overwolf suggested to reach out to your 3rd party for support, this was announced today.
https://curseforge-ideas.overwolf.com/ideas/CF-I-2731

**Comment by peterix** [comment] 2022-05-27 01:59
I am not going to touch anything related to CurseForge until the TOS is fixed.
