### ISSUE TITLE
Offline Mode not working

### ISSUE THREAD

**Issue by AlessioGr** [MultiMC/Launcher#4433] opened 2022-01-18 10:15 UTC
### Operating System

Windows

### Description of bug

When I click on launch offline, the launcher is stuck at the following message (1.18 vanilla):
![image](https://user-images.githubusercontent.com/70709113/149917107-737d5228-ce10-43e5-a1e7-15e626794085.png)

I cannot close that message without destroying multimc in the task manager.

Mojang servers are currently down as of me writing this issue, so that's quite annoying. I'm using a Microsoft account.

This is the console output of MultiMC when it's happening:

![image](https://user-images.githubusercontent.com/70709113/149918109-8d937570-97ec-4380-9058-14baf65f70ec.png)

### Steps to reproduce

1. Get MultiMC 0.6.14-develop-3168
2. Launch a Minecraft 1.18.1 instance by clicking Launch offline. This is also reproducable on other versions

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by PanoptesDreams** [comment] 2022-01-18 10:28
I am experiencing the same issue (right now, also due to the servers being down)
To add, the authentication feedback window loops around as can be seen in the log above

**Comment by Thirace446** [comment] 2022-01-18 10:32
I am experiencing the same issue .
And when I log out, I can't log back in.

**Comment by PanoptesDreams** [comment] 2022-01-18 10:37
WORKAROUND: Create a firewall rule completely blocking MultiMC
After some thinking MultiMC will prompt for your Offline name then launch
*yay* 🙄

**Comment by henos1029** [comment] 2022-02-21 00:56
I also have this issue, and i will only prompt me for my name when i turn my wifi off, even when mojang servers are not down

**Comment by PanoptesDreams** [comment] 2022-02-21 01:48
> I also have this issue, and i will only prompt me for my name when i turn my wifi off, even when mojang servers are not down

Assuming your computer is connected to the internet through WiFi, Of course it won't be able to connect if you turn it off. What are you even saying??

**Comment by henos1029** [comment] 2022-02-21 02:24
> > I also have this issue, and i will only prompt me for my name when i turn my wifi off, even when mojang servers are not down
> 
> Assuming your computer is connected to the internet through WiFi, Of course it won't be able to connect if you turn it off. What are you even saying??

when i click launch offline, it will try and launch online anyway, and only launch offline when i turn my wifi off

**Comment by PanoptesDreams** [comment] 2022-02-21 03:04
> when i click launch offline, it will try and launch online anyway

Ok yes, this is the bugged behavior related to Microsoft Authentication services
See Also: https://github.com/PolyMC/PolyMC/issues/85

A temporary fix is to go into your firewall and completely block MultiMC and prevent it from reaching out to XBL/MSA


> , and only launch offline when i turn my wifi off

And yes. You can't play online with your internet connection disconnected. Unless there's something else your not mentioning?

It helps if you're concise in your report, otherwise people don't know what you're talking about, saying or trying to ask.

**Comment by henos1029** [comment] 2022-02-21 03:41
> > when i click launch offline, it will try and launch online anyway
> 
> Ok yes, this is the bugged behavior related to Microsoft Authentication services See Also: [PolyMC/PolyMC#85](https://github.com/PolyMC/PolyMC/issues/85)
> 
> A temporary fix is to go into your firewall and completely block MultiMC and prevent it from reaching out to XBL/MSA (as mentioned above)
> 
> > , and only launch offline when i turn my wifi off
> 
> And yes. You can't play online with your internet connection disconnected. Unless there's something else your not mentioning?
> 
> It helps if you're concise in your report, otherwise people don't know what you're talking about, saying or trying to ask.

when i click on launch offline, i dont want it to launch online

**Comment by PanoptesDreams** [comment] 2022-02-21 04:37
> when i click on launch offline, i dont want it to launch online

Cool, well as you can read, that function doesn't work at the moment.
If you want to play offline while maintaining your internet connection do as instructed above:

Create a Firewall rule blocking MultiMC from accessing the internet. Restart MultiMC. Done.

You will still need to sign in to a Minecraft account at least once to generate a login token that can be used offline.

**Comment by PanoptesDreams** [comment] 2022-02-21 04:52
> when i click launch offline, it will try and launch online anyway, and only launch offline when i turn my wifi off

For clarity's sake; it's not trying to 'launch online' The launcher detects an internet connection and is trying to get MSA authentication despite "launching offline". Once it gets a token it will play in offline mode. (this is the bugged behavior)

**Comment by InsaneJ** [comment] 2022-03-16 14:01
Currently the Microsoft authorization servers are offline. Because of the bug in this issue it is currently impossible to play Minecraft using MultiMC.

Getting the same behavior as described above. MultiMC tries to go online with a message "Getting authorization to access Mojang services". This dialogue window keeps reappearing (retries?) and can not be closed by clicking the X thus making MultiMC unresponsive. Only way to get around that is to kill the MultiMC process entirely.

**Comment by Fixer-007** [comment] 2022-03-16 14:52
Same problem InsaneJ is having, Offline mode needs rework to handle such cases

**Comment by PanoptesDreams** [comment] 2022-03-17 01:39
> Currently the Microsoft authorization servers are offline. Because of the bug in this issue it is currently impossible to play Minecraft using MultiMC.
> 
> Getting the same behavior as described above. MultiMC tries to go online with a message "Getting authorization to access Mojang services". This dialogue window keeps reappearing (retries?) and can not be closed by clicking the X thus making MultiMC unresponsive. Only way to get around that is to kill the MultiMC process entirely.

Guys, read the comments. There's a workaround.

Block multimc in your wirewall

**Comment by strogonoff** [comment] 2022-04-16 12:48
@PanoptesDreams but you still need to log in with your MS account at least once per computer, right? Per https://github.com/MultiMC/Launcher/issues/4433#issuecomment-1046467257.

**Comment by PanoptesDreams** [comment] 2022-04-16 16:02
> @PanoptesDreams but you still need to log in with your MS account at least once per computer, right? Per https://github.com/MultiMC/Launcher/issues/4433#issuecomment-1046467257.

Yes, and there's nothing wrong with that. This ensures the client does own the game and gets an authentication token.

Asking a player to go online just once is not much to ask.

**Comment by strogonoff** [comment] 2022-04-16 17:10
Absolutely, for those who don't mind giving MS their phone number.

**Comment by PanoptesDreams** [comment] 2022-04-17 04:01
> Absolutely, for those who don't mind giving MS their phone number.

If you're really concerned about your privacy that much then buy a burner.
Oh and delete your GitHub account because Microsoft own this too 👍

Your comments are off topic and contribute nothing.

**Comment by strogonoff** [comment] 2022-04-17 09:40
If player needs to be online in order to use offline mode, then as far as I’m concerned offline mode is broken.

Burner phones or not is really not the point (although there’s a good chance after player gives up their phone number once they may well be required to confirm the same number at a later point, knowing the unpredictability of Microsoft authentication systems I’d be very cautious about recommending this route).

Either way, please stop derailing the thread with your personal takes on why privacy doesn’t matter and stay on the subject, which is malfunctioning offline mode.

**Comment by PanoptesDreams** [comment] 2022-04-17 09:47
> If player needs to be online in order to use offline mode, then as far as I’m concerned offline mode is broken.

🤦‍♀️ No shit. But the player needs to authenticate at least once to verify they own the game. Otherwise the launcher is just acting as an avenue to pirate. Go read the related threads

> Burner phones or not is really not the point (although there’s a good chance after player gives up their phone number once they may well be required to confirm the same number at a later point, knowing the unpredictability of Microsoft authentication systems I’d be very cautious about recommending this route).
> 
> Either way, please stop derailing the thread with your personal takes on why privacy doesn’t matter and stay on the subject, which is malfunctioning offline mode.

What are you on boy?
You mentioned a phone number being a point of privacy concern and then say I'm going off topic.

I never gave a take about why privacy "doesn't matter". It does and is very important. Stop putting words in other mouths.

**Comment by xcfrg** [comment] 2022-04-17 16:20
Just to clarify, offline mode is working as intended as long as the user has logged in once?

**Comment by AlessioGr** [comment] 2022-04-17 16:23
I didn't follow the entire conversation but I hope it's clear that, at least when I opened this issue, offline mode is not working as intended.

**Comment by PanoptesDreams** [comment] 2022-04-18 02:56
> Just to clarify, offline mode is working as intended as long as the user has logged in once?

Yes, make sure you update to the latest version

> I didn't follow the entire conversation but I hope it's clear that, at least when I opened this issue, offline mode is not working as intended.
> 
> Did it get fixed already?

This was fixed in the latest release 0.6.15:

• Scan for changes to Minecraft entitlements on account refresh (to make sure we detect changes to entitlements).
• Add some more logging to interaction with Minecraft services and authentication (profile fetching, etc.).

**Comment by xcfrg** [comment] 2022-04-19 14:17
@AlessioGr Can you reproduce on the latest stable release?

**Comment by PanoptesDreams** [comment] 2022-04-19 15:40
> @AlessioGr Can you reproduce on the latest stable release?

I'm not Alessio.. but it does appear to be fixed

**Closed** 2022-06-30 10:47 UTC
Labels: bug, Auth
