### ISSUE TITLE
The ability to export for curseforge

### ISSUE THREAD

**Issue by joshuaepstein** [MultiMC/Launcher#4485] opened 2022-02-03 19:44 UTC
### Role

Modded Minecraft

### Suggestion

The ability to export a profile to: 1: Upload to curseforge and 2: Share with others to import (Importing from zip/url)

### Benefit

To make an easier way to share profiles and modpacks with others.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

To be able to click: 'Export Instance' and get an option to export either just the full instance in a zip. Or, you can export like the CurseForge app. Where it get the modlist and creates an html file with that information. This can then be imported by other people in the import from zip.

**Comment by phit** [comment] 2022-02-03 19:45
Duplicate of https://github.com/MultiMC/Launcher/issues/3707

**Closed by phit** 2022-02-03 19:45 UTC
