### ISSUE TITLE
Close MultiMC Launcher window as soon as Minecraft starts

### ISSUE THREAD

**Issue by Teslicek** [MultiMC/Launcher#4007] opened 2021-08-15 12:55 UTC
### Role

I just play ordinary Minecraft with Fabric mods

### Suggestion

I want MultiMC to add a setting (a checkbox) to choose, if I want the MultiMC Launcher window to close automatically as soon as Minecraft starts or not.

### Benefit

Because it's a nice little feature that I would really appreciate if it had and it would save a few unnecessary clicks (+I could finally sleep peacefully).

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by LaxWasHere** [comment] 2021-12-26 02:01
pls ty

**Comment by phit** [comment] 2022-12-30 21:16
Duplicate of https://github.com/MultiMC/Launcher/issues/3406

**Closed by phit** 2022-12-30 21:16 UTC
Labels: suggestion
