### ISSUE TITLE
Add a possibility to add non-premium accounts.

### ISSUE THREAD

**Issue by Kasia1403** [MultiMC/Launcher#4636] opened 2022-04-11 10:09 UTC
### Role

Vanilla Minecraft and also modded Minecraft

### Suggestion

Add a possibility to add non-premium accounts.

### Benefit

So that I will not have to waste money for buying Minecraft premium ( I'm disabled and I don't have money and also my mom doesn't like to waste money ).

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Xetaxheb** [comment] 2022-04-11 22:15
Duplicate of #1102
will likely be similarly rejected and you shouldn't have checked that checkbox
also lol no multimc doesn't allow you to play minecraft without owning it

**Closed** 2022-04-12 16:45 UTC

**Comment by Yupoman** [comment] 2022-07-21 22:18
Yes bro, try to get a game from a stranger or win the lottery, maybe in 10 years ~~or never~~ you will get the game and you can use MultiMC!

MultiMC is terrible shit, they lick mojang's ass but they don't even use the official launcher. I recommend looking for another launcher that allows you to create profiles like LauncherFenix or MultiMC cracked and that's it.
...
![notch](https://user-images.githubusercontent.com/70600879/180323420-c01ce462-159d-4b1e-82dc-9a932d452103.png)
