### ISSUE TITLE
Exporting 1.19.4 doesnt include configs

### ISSUE THREAD

**Issue by Parilia** [MultiMC/Launcher#5101] opened 2023-03-22 01:13 UTC
### Operating System

Windows

### Description of bug

Extracting a 1.19.4 pack both modrinth and multimc does not include configs or anything other than the index file.

### Steps to reproduce

Export modpack

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment] 2023-04-10 14:01
I'm unable to reproduce this, did you uncheck the configs option? Otherwise can you zip up the pack you are trying to export to help test this.

**Comment by fathulfahmy** [comment] 2023-05-27 13:33
I was also facing the same issue when exporting a modrinth modpack.

Steps to reproduce:
1. Add instance
2. Edit instance
3. Install fabric
4. Add mods to `/.minecraft/mods/` folders
5. Launch the game
6. Edit mod settings
7. Close the game
8. Export to modrinth as 'test.mrpack'
9. Add instance
10. Import from zip
11. Check config file

**Comment by phit** [comment] 2024-12-21 12:45
should have been fixed with https://github.com/MultiMC/Launcher/pull/5389

**Closed as completed by phit** 2024-12-21 12:45 UTC
Labels: bug, needs-repro
