### ISSUE TITLE
Discord RPC

### ISSUE THREAD

**Issue by BoBkiNN** [MultiMC/Launcher#4421] opened 2022-01-11 16:59 UTC
### Role

play modpacks and convert other instances, allow discord users see what instance are you playing

### Suggestion

You can change in settings your default rpc, that will be displayed in discord activity. And add rpc setting for every instance

### Benefit

this will be nice and useful feature

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

offical FAQ about Discord RPC https://discord.com/developers/docs/topics/rpc
hope this will be added)

**Comment by phit** [comment] 2022-01-11 18:53
Duplicate of https://github.com/MultiMC/Launcher/issues/3070

**Closed by phit** 2022-01-11 18:53 UTC
