### ISSUE TITLE
a few strings don't get translated when changing languages

### ISSUE THREAD

**Issue by Ticha22608** [MultiMC/Launcher#4534] opened 2022-02-22 13:55 UTC
### Operating System

Windows

### Description of bug

some strings, like the "close" and "help" buttons in settings and the create instance menu, and the total playtime string don't get changed from english when changing languages
here's how it looks in english:
![image](https://user-images.githubusercontent.com/40746497/155145686-979e1a16-0975-435d-8c97-ccc634d5e14d.png)
as you can see, normal
now, i'll change to another language, one with 100% completion
i'll try with spanish:
![image](https://user-images.githubusercontent.com/40746497/155145897-12792801-2625-4ef9-a48e-e494c344225d.png)
the problematic strings are still in english, even after restarting mmc
now, i'll try with another 100% language (german) to prove that it's not a translation issue:
![image](https://user-images.githubusercontent.com/40746497/155146255-8740672a-e881-4b7f-86ad-dfbb0e3a74f5.png)
as you can see here, although the minute abbreviation changed from "m" to "min", the total playtime (and the other problematic) strings are still in english

### Steps to reproduce

1. change languages
2. look at the buttons and total playtime

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment] 2022-02-22 16:37
Duplicate of https://github.com/MultiMC/Launcher/issues/1834

**Closed by phit** 2022-02-22 16:37 UTC
Labels: bug
