### ISSUE TITLE
Play offline button not work

### ISSUE THREAD

**Issue by FazziCLAY** [MultiMC/Launcher#5182] opened 2023-06-11 15:01 UTC
### Operating System

Linux

### Description of bug

Play offline button not work

### Steps to reproduce

Click to version & start

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment] 2023-06-11 18:20
what doesn't work?

**Comment by FazziCLAY** [comment] 2023-06-11 18:58
> what doesn't work?

when you click nothing happens, the launcher continues to log in through the microsoft account ignoring my clicks

**Comment by phit** [comment] 2023-06-11 19:03
ah so this, duplicate of https://github.com/MultiMC/Launcher/issues/5078

**Closed as completed by phit** 2023-06-11 19:03 UTC
Labels: bug

**Comment by FazziCLAY** [comment] 2023-06-11 19:05
sorry

**Comment by phit** [comment] 2023-06-11 19:06
no worries, sorry that I don't have a fix at this time
