### ISSUE TITLE
MMC deleting profile on failed auth.

### ISSUE THREAD

**Issue by Shadefang** [MultiMC/Launcher#5474] opened 2024-07-19 00:40 UTC
### Operating System

Windows

### Description of bug

Upon trying to launch an instance I was given a message to refresh my minecraft account.  Doing so failed, as it appears minecraft's auth servers are currently down. When it failed, the profile was removed from the list.

I would expect MMC upon receiving a "service unavailable" response from the auth servers to at very least retain the existing profile, and hopefully allow for launching offline.

### Steps to reproduce

I would assume attempting to log in (or possibly refresh) an account while the auth servers are down. This is not something I have the capabilities of testing repeatedly as the profile no longer exists and I can't create a new one, as the auth servers are down.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Talon-1** [comment] 2024-07-19 00:51
Same problem, this is the 2nd time my account poofed from auth server issues, I too wish I could at least launch my single player worlds while auth is down.

**Comment by HoneyPS** [comment] 2024-07-19 00:56
Im having the zac same issue i tried chaning my login from codes to my number to my finger print and still haunted by the error to access token. 
![Screenshot 2024-07-19 105010](https://github.com/user-attachments/assets/d709f22d-e15e-495b-bba7-1908bad0ac4a)

**Comment by DarianLStephens** [comment] 2024-07-19 00:57
Exact same problem just happened to me.
I had launched the game just fine a few hours ago, but now it's apparently expired, and wanted me to log in again with Microsoft.
I did, then it failed to get the access token and deleted my account from the list.

**Comment by iiPythonx** [comment] 2024-07-19 01:12
Xbox services regarding login are currently offline: https://support.xbox.com/en-US/xbox-live-status.
You're gonna have to wait for them to come back online.

**Comment by Shadefang** [comment] 2024-07-19 01:14
> Xbox services regarding login are currently offline: https://support.xbox.com/en-US/xbox-live-status. You're gonna have to wait for them to come back online.

I'm aware they're down, and that that's why I'm having access issues. There's a reason my issue isn't just "I can't access my game" and instead is "Trying to access the game while the auth servers were down deleted my profile."

**Comment by iiPythonx** [comment] 2024-07-19 01:17
Just realized the issue title, my bad. I guess it would be smart for the launcher to keep the existing profile but regardless it's still going to require a re-login with Xbox services since the sessions have been invalidated.

**Comment by Shadefang** [comment] 2024-07-19 01:20
somewhat fair, assuming the sessions were invalidated by something _other_ than the fact the servers are down.  Frankly, if the servers are unreachable, and you're on an account that was previously authorized it should just let you launch offline.

**Comment by phit** [comment] 2024-07-19 07:05
Duplicate of https://github.com/MultiMC/Launcher/issues/5078

**Closed as completed by phit** 2024-07-19 07:05 UTC
Labels: bug

**Comment by Shadefang** [comment] 2024-07-19 09:25
> Duplicate of #5078

Should I bring up the additional problem in that issue thread? That in addition to not working offline the profile gets deleted (which also means the suggested proxy workaround won't work, as there's no profile to launch offline)

**Comment by phit** [comment] 2024-07-19 12:34
the account removal is intentional and was added with https://github.com/MultiMC/Launcher/pull/4998, obviously it shouldnt happen in case of server issues though
