### ISSUE TITLE
CurseForge - Issue

### ISSUE THREAD

**Issue by RobertLSnead** [MultiMC/Launcher#4697] opened 2022-05-19 23:10 UTC
### Operating System

Linux

### Description of bug

I am unable to add an instance from curseforge, both by the search and through the .zip method.
I get the unable to process mod ids, when trying the .zip method.

### Steps to reproduce

1. Click add instance
2. try to add or search curseforge
3. nothing shows

1. click add instance
2. add through .zip
3. error processing mod ids

### Suspected cause

curseforge format might have changed since last mmc update

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by otakup0pe** [comment] 2022-05-19 23:17
Probable dupe of https://github.com/MultiMC/Launcher/issues/4695

**Comment by WyFryMU** [comment] 2022-05-19 23:28
Newest update removed FTB and curseforge integration so that's why you can find those packs on multimc. Not sure why the .zip wouldnt work though.

**Comment by SunSeek** [comment] 2022-05-19 23:38
This is an issue on Curseforge's side. If any mod creater disallowed 3rd party downloads and they are in the pack, the whole pack installation will fail, so import via zip is unreliable. This is not OS dependent.

**Comment by Azrez2** [comment] 2022-05-20 02:35
> This is an issue on Curseforge's side. If any mod creater disallowed 3rd party downloads and they are in the pack, the whole pack installation will fail, so import via zip is unreliable. This is not OS dependent.
Is there a good workaround for this, or will I have to install the curseforge app?

**Comment by phit** [comment] 2022-05-20 10:34
Curseforge integration has been shut down and is removed in the newest development versions https://github.com/MultiMC/Launcher/commit/0a827ba70e6ef20187f8507a536d54a8441020dc

**Closed by phit** 2022-05-20 10:34 UTC
Labels: close:wai

**Comment by RobertLSnead** [comment] 2022-05-20 19:06
CurseForge doesn't even offer support for linux other than for wow, what a big shame.
RIP....
