### ISSUE TITLE
Deleted mods go to recycle bin?

### ISSUE THREAD

**Issue by KrisCris** [MultiMC/Launcher#4397] opened 2021-12-31 00:33 UTC
### Role

play modded minecraft

### Suggestion

Deleted mods go to recycle bin

### Benefit

in case you accidentally clicked the wrong button

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The delete and enable buttons are TOO close to each other, and I accidentally clicked delete - half of my mods are gone and I have no idea what they were...

**Comment by phit** [comment] 2021-12-31 12:56
Duplicate of https://github.com/MultiMC/Launcher/issues/3669

**Closed by phit** 2021-12-31 12:56 UTC
