### ISSUE TITLE
MSA Secrets via UI?

### ISSUE THREAD

**Issue by Schmensch** [MultiMC/Launcher#4366] opened 2021-12-17 19:55 UTC
### Role

As a Dev and Maintainer of packages, It would be very to not have to compile secrets in.

### Suggestion

Add a UI for adding your own MSA secrets after compiling.

### Benefit

Making MultiMC available on more distros by making it way easier to package.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Make an easy UI to add MSA Secrets. Nothing special, just a box to input the Secret key and an explanation of what this is, how you can get it, etc...

I'm not saying that MultiMC should drop pre-installed secrets that can't easily be read out. These should still exist to make MultiMC more accessible.

The current state is just really, really, really shitty for package maintainers. As a package maintainer you currently only have 2 options:

1. Add your own secrets, which is a very huge risk and not an option for source-based distros like Gentoo
2. Tell users how to compile their own secrets in and then how to compile from source. Try to explain this to the usual Ubuntu User.

Both of these are shitty. You can make option 2 less shitty by adding a user-friendly menu with instructions on how to retrieve a MSA secret and an easy input box for the secrets. This reduce the risk taken by packagers by almost 100%, while not requiring to compile everything from source.

This shouldn't even be that hard to implement.

**Comment by phit** [comment] 2021-12-17 19:58
Duplicate of https://github.com/MultiMC/Launcher/issues/4360

**Closed by phit** 2021-12-17 19:58 UTC
