### ISSUE TITLE
"Most Recent" version option to automatically keep Minecraft(/mods) up to date

### ISSUE THREAD

**Issue by timgblack** [MultiMC/Launcher#5088] opened 2023-02-26 00:48 UTC
### Role

I play on Minecraft Realms

### Suggestion

Have a "Most Recent" version that automatically selects the most up-to-date version of Minecraft (or potentially any mod)

### Benefit

Essentially a minor QOL - it saves me from going in-game and failing to connect to Realms, exiting the game, and updating Minecraft's version manually

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment] 2023-02-26 08:23
Duplicate of https://github.com/MultiMC/Launcher/issues/4293

**Closed as completed by phit** 2023-02-26 08:23 UTC
Labels: close:duplicate
