### ISSUE TITLE
Cannot select an account in the Account Manager

### ISSUE THREAD

**Issue by RobinD3l** [MultiMC/Launcher#4268] opened 2021-11-21 13:22 UTC
### Description of bug

I downloaded the newest update from the launcher and now in the account manager i cannot select a specific account because it always selects every account or no account and when i start the game it always starts with the account that is the first in the list. i tried deleting the accounts.json file but that didnt fix it. here a screenshot [https://imgur.com/a/GQDap0j](https://imgur.com/a/GQDap0j)

### Steps to reproduce

Add multiple accounts and then try to select one of them

### Suspected cause

I dont know maybe something in the newest version

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment] 2021-11-21 13:28
Duplicate of GH-4265.

**Closed by jamierocks** 2021-11-21 13:28 UTC
Labels: bug
