### ISSUE TITLE
Cannot download certain modpack on Linux

### ISSUE THREAD

**Issue by Rafii2198** [MultiMC/Launcher#4414] opened 2022-01-08 02:08 UTC
### Operating System

Linux

### Description of bug

Whenever I try to download a modpack called ATS Challenge which is private FTB modpack, I get this error 
![obraz](https://user-images.githubusercontent.com/26695327/148627335-6598c1df-2475-4744-a6e8-83474d4b12ed.png)
 This only happens on Linux, I downloaded it on Windows without a problem.
 When I had my old MacBook it also happened there but I don't have it now.

### Steps to reproduce

* Add private FTB modpack, code is `ats`
* Try to download it

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment] 2022-01-08 17:31
Duplicate of https://github.com/MultiMC/Launcher/issues/4370

**Closed by phit** 2022-01-08 17:31 UTC
Labels: bug
