### ISSUE TITLE
Minecraft alpha without sound

### ISSUE THREAD

**Issue by AGAMEN0M** [MultiMC/Launcher#4849] opened 2022-07-22 22:52 UTC
### Operating System

Windows

### Description of bug

Minecraft sound error inf-20100618, a1.0.4, a1.0.5_01, a1.0.11, a1.0.14, a1.0.15, a1.0.16, a1.0.17_02, a1.0.17_04, a1.1.0, a1. 1.2.

And for this not to happen, it is necessary to start MultiMC with the PC offiline.

Please add a way for the launcher to run these versions in offline mode or fix this bug.

### Steps to reproduce

Just start the MultiMC with the internet on and off and you can see the difference.
But only in versions inf-20100618, a1.0.4, a1.0.5_01, a1.0.11, a1.0.14, a1.0.15, a1.0.16, a1.0.17_02, a1.0.17_04, a1.1.0, a1. 1.2.

### Suspected cause

Maybe something related to the offline mode is not working properly.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by arthomnix** [comment] 2022-12-04 09:56
This happens because older game versions try to download resources from somewhere that no longer exists, and happens on the vanilla launcher too.
As a workaround you can block Internet access to the instance by adding the java argument `-DsocksProxyHost=0.0.0.0` (this makes it try to use a nonexistent proxy).

**Comment by phit** [comment] 2023-02-15 16:46
Duplicate of https://github.com/MultiMC/Launcher/issues/3807

**Closed by phit** 2023-02-15 16:46 UTC
Labels: bug, minecraft
