### ISSUE TITLE
App freezes on attempt to edit instance after leaving a game

### ISSUE THREAD

**Issue by AngleWyrm10** [MultiMC/Launcher#3862] opened 2021-06-14 19:32 UTC
### Operating System
Windows 10
MultiMC v0.6.11.1430
Forge v36.1.31
Minecraft v1.16.5

### Description of bug
Application hangs (not responding) when attempting to edit instance after returning from a playthrough. 

### Steps to reproduce
Start a game, play for a sec
Save and quit game
Quit minecraft
Attempt to edit instance

### Suspected cause
Might be related to Issue #2610 

### This issue is unique
- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by spannerman79** [comment] 2021-06-15 00:03
This is more of a duplicate of #3811

**Comment by Xenapte** [comment] 2021-06-17 05:51
I think that probably was from large log files. I once played on a server with a bug that caused error spamming in client log (the gameplay was not affected though) and generated >10MB log files each time. And MultiMC most time froze when I tried to edit that instance after playing in that server in the last launch (it would always freeze if I tried to edit that instance while playing, since it auto navigated to logs page).

**Comment by Arrowpuppet** [comment] 2022-01-22 04:01
Looks like it's definitely the large log files causing the app to hang. I lowered the line limit on the logs to ~20k and the issue stopped. (unfortunately this means the log that's shown in the launcher will be mostly useless if it's being filled with error spamming, but it' not too much of a hassle to grab the log files manually.)

**Comment by ljcool2006** [comment] 2024-02-05 04:56
Was just able to reproduce this.

**Comment by phit** [comment] 2024-12-22 21:03
closing as duplicate of https://github.com/MultiMC/Launcher/issues/4228 as it has the better title

**Closed by phit** 2024-12-22 21:03 UTC
Labels: bug, needs-repro
