### ISSUE TITLE
Allow launching instance with specified profile

### ISSUE THREAD

**Issue by naqaden** [MultiMC/Launcher#3116] opened 2020-04-25 09:08 UTC
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Summary of the suggestion:
----------------------------------------------
- A new command line option to specify which profile to use when launching an instance
- A new instance setting to set a default profile

What should happen:
------------------------------
MultiMC selects a profile to use based on the following priority:
1. command line profile, if supplied
2. instance setting's default profile, if set
3. the global default profile as we know it

**Comment by golfermatt** [comment] 2020-04-25 10:29
Multimc doesn't use profiles like the vanilla launcher does, not even behind the scenes. 
If you're trying to get Optifine working [the wiki](https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine) has a guide on that. It can also be installed like a normal mod via forge or fabric (compatibility mods may be required). 
Besides that, i can only think of one other thing that would need this - a cheat client. Peterix  said that the way these clients launch will not ever be supported in #1772. There are ways that you can make it work, but nobody is going to help you with that.

If there's a reason why you need this feature, please tell us and we might be able to help you - but I'm fairly sure that this isn't going to happen.

**Comment by naqaden** [comment] 2020-04-25 10:47
I'm a modder. I have two profiles saved in MultiMC for testing purposes. I can't leave one profile set to default when testing multiplayer mods. I have to leave my profile set to No Default Account and manually select each profile to run together in multiplayer, every time. I'm looking for a convenient solution to this, though I understand my case is an edge one.

**Comment by golfermatt** [comment] 2020-04-25 10:51
Just making sure, you want an easy way to launch different minecraft accounts?

**Comment by naqaden** [comment] 2020-04-25 10:52
Yes.

**Comment by golfermatt** [comment] 2020-04-25 10:54
Gotcha. In that case i don't know of anything that might be able to help, but I hope that you find something.

**Comment by dazoe** [comment] 2020-08-08 16:19
I too was looking for an option like this... maybe something like when the instance is selected it automatically changes the selected profile to the last one used with that instance. Or have it change to a profile that is currently not in use.

**Comment by dazoe** [comment] 2020-08-14 13:19
I just found out that if i don't have a profile selected in the upper right and go to launch an instance it asks which profile to use. That is a close workaround

**Comment by naqaden** [comment] 2020-08-14 18:24
Yeah, I described that to ghost [above](https://github.com/MultiMC/MultiMC5/issues/3116#issuecomment-619359647), but IMO manually selecting post-launch is practically the same as manually selecting pre-launch.

**Comment by naqaden** [comment] 2020-08-14 18:24
Yeah, I described that to ghost [above](https://github.com/MultiMC/MultiMC5/issues/3116#issuecomment-619359647), but IMO manually selecting post-launch is practically the same as manually selecting pre-launch.

**Comment by Scotsguy** [comment] 2021-03-08 14:21
Duplicate of #3411

**Comment by naqaden** [comment] 2021-03-08 19:22
> 
> 
> Duplicate of #3411

You've exposed my time travel ability!

**Comment by naqaden** [comment] 2021-08-14 17:57
@peterix @scotsguy Kindly reopen this issue. It wasn't a big deal when this was closed as a "duplicate" of a _newer_ issue, but since then the newer issue was closed after some unwanted bounty offers.

We have no control over what other users request or offer in our issues' comments, so an issue's status shouldn't suffer for it. If this feature request isn't feasible, that's another (more constructive) story we can learn from, hopefully toward a feasible alternative.

**Comment by peterix** [comment] 2021-08-14 18:20
Makes sense.

**Comment by ejm554** [comment] 2022-10-25 15:01
> Sorry for the misunderstanding. I was getting my vanilla and multimc terminology mixed up.

For all the time I've been playing Minecraft, usually with MultiMC, I often hear the word "profile" bandied about, but I admit to being unclear about its definition, and I haven't been able to locate anything that describes it unambiguously.

Is the @ghost user saying that "profile" means one thing in MultiMC and something else in "vanilla?" (Or maybe they meant MultiMC vs. _the official Minecraft launcher_?)

**Comment by naqaden** [comment] 2022-10-25 16:04
> MultiMC vs. _the official Minecraft launcher_

That. At the time, Minecraft accounts were stored in MultiMC as profiles. Now the UI refers to them as accounts, though you can still find references to profile in the wiki and changelog. Whereas in the official Minecraft launcher and CurseForge app, profiles store different Minecraft installations, equivalent to MultiMC instances, like you said.

By the way everyone, the #1795 command line suggestion was implemented:
```
GH-1795: Added terminal launch option to use a specific Minecraft profile (in-game player name). 
Used like this: ./MultiMC --launch 1.17.1 --profile MultiMCTest --server mc.hypixel.net
```

I'll leave this open in case my 2nd suggestion setting (per instance defaults) is on the table. Otherwise this could be closed.

**Comment by Merlin72875** [comment] 2022-12-20 17:31
2+ years and still seeing duplicates of this going around. I have "instances" that I ONLY ever use one or another MC "account" (profile, player, etc) with, I'd love the idea of just launching that icon without having to hit the dropdown to change to the account, then launching the instance.  Thanks!

**Comment by naqaden** [comment] 2022-12-20 18:57
A decent workaround for now is to make a shortcut to MultiMC.exe from your MultiMC installation.

Right click the shortcut and open **Properties**. In the **Shortcut** tab, at the end of the **Target** field, add these parameters:
` --launch "INSTANCE_FOLDER" --profile "PROFILE"`

Replace `INSTANCE_FOLDER` with the instance's folder name, _not_ necessarily the instance's name you see in MultiMC. They're _probably_ the same, but to be sure, right click the instance in MultiMC to open **Instance Folder** and see the folder's name.

Replace `PROFILE` with any name from the MultiMC account drop-down. If you open **Manage Accounts** from there, or the **Accounts** tab from **Settings**, choose any name from the **Profiles** column.

In the end, your shortcut's **Target** field should look something like this:
`"C:\Program Files (x86)\MultiMC\MultiMC.exe" --launch "Alt Instance" --profile "AltUsername"`

**Closed** 2024-06-14 05:48 UTC
Labels: suggestion
