### ISSUE TITLE
Add a “Search Loader Mods” feature

### ISSUE THREAD

**Issue by unusualotter** [MultiMC/Launcher#4578] opened 2022-03-14 01:03 UTC
### Role

I play modded Mc and make modpacks

### Suggestion

Add a search mods bar in the loader mods section 

### Benefit

Always have mods, and attract more users

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

You could use the API of https://modrinth.com/ because it’s fully open source

**Comment by phit** [comment] 2022-03-14 11:15
Duplicate of https://github.com/MultiMC/Launcher/issues/3055

**Closed by phit** 2022-03-14 11:15 UTC
Labels: suggestion
