### ISSUE TITLE
Keeping track of what version you downloaded

### ISSUE THREAD

**Issue by Caedis** [MultiMC/Launcher#4449] opened 2022-01-24 23:59 UTC
### Role

I play modded Minecraft

### Suggestion

Log what version was downloaded when adding an instance

### Benefit

So that players know what version of a pack they downloaded

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Either keep track of the version or the name of the zip file that was used to create an instance.

**Comment by phit** [comment] 2022-01-25 08:05
duplicate of https://github.com/MultiMC/Launcher/issues/4431, https://github.com/MultiMC/Launcher/issues/3769 and a bunch of others related to pack updating that have this as a prerequisite

**Closed by phit** 2022-01-25 08:05 UTC
