### ISSUE TITLE
Microsoft Account "Doesn't own Java Edition"

### ISSUE THREAD

**Issue by Axyl69** [MultiMC/Launcher#4215] opened 2021-11-01 21:48 UTC
### Operating System

Windows

### Description of bug

![image_2021-11-01_174628](https://user-images.githubusercontent.com/69871266/139746393-1fccf485-85f0-48e5-a82c-1baf784316c7.png)
After trying to add my account which is a Microsoft account because I migrated. This account is the same I use to log in to the normal launcher so I do own Minecraft Java Edition with it.

### Steps to reproduce

1. Download MultiMC
2. Add Accounts
3. Add Microsoft
4. Log in through browser
5. the error in the image shows up

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by peterix** [comment] 2021-11-01 22:02
The Mojang servers say you don't have a Java profile.

**Comment by peterix** [comment] 2021-11-01 22:02
```
    if (error == QNetworkReply::ContentNotFoundError) {
        m_data->minecraftProfile = MinecraftProfile();
        finishActivity();
        changeState(STATE_FAILED_HARD, tr("Account is missing a Minecraft Java profile.\n\nWhile the Microsoft account is valid, it does not own the game.\n\nYou might own Bedrock on this account, but that does not give you access to Java currently."));
        return;
    }
```

`Content not found` ... `404`

**Comment by peterix** [comment] 2021-11-01 22:17
Is there anything interesting in the `MultiMC.0.log` when this happens?

**Comment by phit** [comment] 2021-11-07 15:04
closing as there hasn't been a reply and without more information this is working as intended

**Closed by phit** 2021-11-07 15:04 UTC
Labels: bug

**Comment by KeithMon** [comment] 2021-12-01 03:24
I am experiencing this exact same issue. The original poster described exactly the issue I'm having. Is there any resolution to this?

**Comment by phit** [comment] 2021-12-01 08:56
switch to the development version, then provide your log and make sure you are using an account that owns the game

**Comment by EntityReborn** [comment] 2022-01-19 23:33
Just got hit with this. Launched MC fine earlier. Tried relaunching MultiMC, removing and readding the account, etc.

**Comment by MacAttack-UK** [comment] 2022-01-19 23:49
FYI: I've also just had the same thing, was perfectly fine a week or so ago when I last played but just now it said I don't own Minecraft. I migrated my account to Microsoft a few months ago and after re-authorising MultiMC to use my account again it fixed my issue. I'm using the Dev version.

**Comment by TBG-FR** [comment] 2022-05-06 20:49
Facing this issue right now... Can't start Minecraft from MultiMC, even after re-authenticating through Microsoft

**Comment by TBG-FR** [comment] 2022-05-06 20:51
See #4670

**Comment by HelpMopDog** [comment] 2022-05-06 21:11
having same issue

**Comment by LordGriefington** [comment] 2022-05-06 21:29
it was working fine a few moments ago. I was loading the vanilla minecraft launcher to test something (launcher from microsoft, it was updating first) . now I get the same issue with multimc. if I am looking at the last comments 39, 37 and 17 minutes ago it could be a general thing. maybe they changed something idk.

**Comment by samhaygood05** [comment] 2022-05-07 01:58
I tried updating to the development build but it didn't change anything

**Comment by LordGriefington** [comment] 2022-05-07 20:38
it was working for me, no clue why it doesn't work for you 🙁

Am Sa., 7. Mai 2022 um 03:58 Uhr schrieb Sam Haygood <
***@***.***>:
