### ISSUE TITLE
Split-Screen Multiplayer Optimizations

### ISSUE THREAD

**Issue by DanKruse731** [MultiMC/Launcher#4922] opened 2022-09-27 22:57 UTC
### Role

Playing Minecraft Locally with Friends

### Suggestion

Since MultiMC is capable of Split-Screen, it would be nice if it were more streamlined.

### Benefit

Because the official means of split-screen are either outdated or inadequate.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I understand that MultiMC wasn't necessarily built for Split-Screen play, but with the controllable mod it works like a charm. The only real problem is that I have to type in the specific offline nicknames for each instance every time. A simple fix would be to save the offline nickname for each instance, but I also think some other improvements could be made, such as saving window positions and making the windows borderless.

**Comment by phit** [comment] 2022-09-28 07:30
Duplicate of https://github.com/MultiMC/Launcher/issues/3335
The other two things with windows are impossible to do for MultiMC

**Closed by phit** 2022-09-28 07:30 UTC
Labels: suggestion
