### ISSUE TITLE
Play Demo Bug (FIXED)

### ISSUE THREAD

**Issue by ngt72** [MultiMC/Launcher#4773] opened 2022-06-13 03:20 UTC
### Description of bug

When I launch any instance it says "This account does not own Minecraft" and ask me if I want to play demo.
First I thought it was an issue from my account, but it wasn't, simply because I can launch game normally in Minecraft Launcher.

![Untitled](https://user-images.githubusercontent.com/107380204/173273145-15918891-6567-4dfb-8f77-5f85bc29a83e.png)

### Steps to reproduce

1. It's a beautiful day and I run MultiMC
2. Can't launch any instances.

### Suspected cause

I've just known that the My Account option on minecraft.net was changed so that you can only edit it on Microsoft website.
Maybe that causes a bug when MultiMC gets information about Minecraft product.

### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Semisol** [comment] 2022-06-13 03:22
Duplicate of #4771?

**Comment by ngt72** [comment] 2022-06-13 03:28
> Semisol
Yes
Seems things've just happened to everyone today

**Comment by LoSpol** [comment] 2022-06-13 04:51
Some Xbox services are down. [Check Here.](https://support.xbox.com/en-US/xbox-live-status)

**Comment by mnfu** [comment] 2022-06-13 05:17
Fixed:
https://twitter.com/MojangStatus/status/1536212024891523073?s=20&t=pa9PlTaf4sR6RPcRPtLeSw

**Closed** 2022-06-13 07:05 UTC
Labels: bug
