### ISSUE TITLE
so annoying

### ISSUE THREAD

**Issue by Shcraftee** [MultiMC/Launcher#5350] opened 2024-02-23 17:43 UTC
### Operating System

Windows

### Description of bug

when i am waiting for it to load it gets stuck at 1 more pixel on my screen and it is so annoying pls fix!!!
![Screenshot (197)](https://github.com/MultiMC/Launcher/assets/161066842/795a3fc6-7375-4197-9c59-ca1166ecf0e4)

### Steps to reproduce

make a new instance an it may happen

### Suspected cause

my internet 💀

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment] 2024-02-23 17:47
Duplicate of https://github.com/MultiMC/Launcher/issues/4329

**Closed as completed by phit** 2024-02-23 17:47 UTC
Labels: bug
