### ISSUE TITLE
Instance update failed because: game update error: could not get the required library file.

### ISSUE THREAD

**Issue by KujouShiori** [MultiMC/Launcher#5387] opened 2024-04-05 03:32 UTC
### Operating System

Windows

### Description of bug

Game files are downloaded from Mojang by default when launching the game, some regions can't download files from mojang servers

### Steps to reproduce

* Add Example
* Select any game version
* Click to start

### Suspected cause

Please consider adding a non-mojang official download source server

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment] 2024-04-05 07:46
Duplicate of https://github.com/MultiMC/Launcher/issues/5273 & https://github.com/MultiMC/Launcher/issues/2246

**Closed as completed by phit** 2024-04-05 07:46 UTC
Labels: bug
