### ISSUE TITLE
Multimc error -1 Help

### ISSUE THREAD

**Issue by tonyblock314** [MultiMC/Launcher#4437] opened 2022-01-20 00:18 UTC
### Description of bug

The game starts to load, then crashes and shows error messages in the log.

### Steps to reproduce

Probbably a specific circumstance but
1.Download MultiMc
2.Add java path
3.Add the vault hunters modpack
4.error occours
MultiMC version: 0.6.14-3001

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.35.107.76]

session.minecraft.net resolves to:
    [3.209.165.60, 3.223.61.237, 52.206.61.151]

textures.minecraft.net resolves to:
    [13.35.105.122, 13.35.105.57, 13.35.105.61, 13.35.105.38]

api.mojang.com resolves to:
    [13.35.117.90]

Minecraft folder is:
C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/instances/Vault-Hunters---Official-Modpack-1.12.2/minecraft

Java path is:
C:/Program Files (x86)/Minecraft Launcher/runtime/java-runtime-beta/windows-x64/java-runtime-beta/bin/java.exe

Checking Java version...
Java is version 17.0.1, using 64-bit architecture, from Microsoft.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/instances/Vault-Hunters---Official-Modpack-1.12.2/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc3/ForgeWrapper-mmc3.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forge/1.16.5-36.2.23/forge-1.16.5-36.2.23-launcher.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/cpw/mods/grossjava9hacks/1.3.3/grossjava9hacks-1.3.3.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/com/electronwill/night-config/core/3.6.3/core-3.6.3.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/com/electronwill/night-config/toml/3.6.3/toml-3.6.3.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/nashorn-core-compat/15.1.1.1/nashorn-core-compat-15.1.1.1.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] appleskin-forge-mc1.16.x-2.2.0
  [✔️] appliedenergistics2-8.4.6
  [✔️] archers_paradox-1.16.5-1.4.0.1
  [✔️] architectury-1.28.48
  [✔️] AutoRegLib-1.6-49
  [✔️] blockcarpentry-1.16-0.4.0
  [✔️] Bookshelf-Forge-1.16.5-10.3.29
  [✔️] Botania-1.16.5-420.1
  [✔️] buildinggadgets-1.16.5-3.8.2
  [✔️] byg-1.3.5
  [✔️] camera-1.16.5-1.0.14
  [✔️] Clumps-6.0.0.27
  [✔️] cofh_core-1.16.5-1.4.0.6
  [✔️] comforts-forge-1.16.5-4.0.1.3
  [✔️] Compressium-1.16.5-1.2.3
  [✔️] Controlling-7.0.0.28
  [✔️] CookingForBlockheads_1.16.5-9.3.4
  [✔️] corpse-1.16.5-1.0.6
  [✔️] CraftTweaker-1.16.5-7.1.2.487
  [✔️] create-mc1.16.5_v0.3.2g
  [✔️] CreateTweaker-1.0.0.26
  [✔️] Cucumber-1.16.5-4.1.12
  [✔️] curios-forge-1.16.5-4.0.5.2
  [✔️] dankstorage-3.19
  [✔️] DarkUtilities-1.16.3-6.0.3
  [✔️] decorative_blocks-1.16.4-1.7.2
  [✔️] DimStorage-1.16.5-4.4.1
  [✔️] easy_villagers-1.16.5-1.0.11
  [✔️] elevatorid-1.16.5-1.7.13
  [✔️] EnderMail-1.16.5-1.2.2
  [✔️] engineersdecor-1.16.5-1.1.15
  [✔️] entitydetectors-1.16.4-1.1.0.1
  [✔️] enviromats-1.16.5-2.0.9.0
  [✔️] fairylights-4.0.5-1.16.5
  [✔️] FastWorkbench-1.16.5-4.6.1
  [✔️] FluxNetworks-1.16.5-6.1.7.12
  [✔️] flywheel-1.16-0.2.5
  [✔️] framedcompactdrawers-1.16-2.2.1
  [✔️] ftb-backups-2.1.2.2
  [✔️] ftb-library-forge-1605.3.4-build.90
  [✔️] furniture-7.0.0-pre19-1.16.3
  [✔️] Hwyla-forge-1.10.11-B78_1.16.2
  [✔️] ImmersiveEngineering-1.16.5-5.0.7-143
  [✔️] industrial-foregoing-1.16.5-3.2.14.6-14
  [✔️] invtweaks-1.16.4-1.0.1
  [✔️] ironchest-1.16.5-11.2.21
  [✔️] ironfurnaces-1.16.5-2.7.7
  [✔️] IronJetpacks-1.16.5-4.2.3
  [✔️] iskallutilities-1.4
  [✔️] ispawner-0.1.7-forge
  [✔️] jei-1.16.5-7.7.1.139
  [✔️] jeiintegration_1.16.5-7.0.1.15
  [✔️] JEITweaker-1.16.5-1.1.0.49
  [✔️] JustEnoughResources-1.16.5-0.12.1.133
  [✔️] Lollipop-1.16.5-3.2.9
  [✔️] masonry-1.16.3-0.3.6
  [✔️] mcjtylib-1.16-5.1.2
  [✔️] mcw-bridges-2.0.1-mc1.16.5
  [✔️] mcw-doors-1.0.5-mc1.16.5
  [✔️] mcw-furniture-2.0.1-mc1.16.5
  [✔️] mcw-roofs-2.0.1-mc1.16.5-4
  [✔️] mcw-windows-2.0.2-mc1.16.5
  [✔️] Mekanism-1.16.5-10.1.1.456
  [✔️] MekanismGenerators-1.16.5-10.1.1.456
  [✔️] metalbarrels-1.16.2-3.3b
  [✔️] mininggadgets-1.7.5
  [✔️] MmmMmmMmmMmm-1.16.5-1.3.1
  [✔️] modular-routers-1.16.5-7.4.0-55
  [✔️] Morpheus-1.16.5-4.2.70
  [✔️] MouseTweaks-2.14-mc1.16.2
  [✔️] movingelevators-1.2.34-mc1.16.5
  [✔️] neoncraft-2.1
  [✔️] OpenLoader-1.16.5-9.0.3
  [✔️] Patchouli-1.16.4-53.2
  [✔️] Placebo-1.16.5-4.6.1
  [✔️] platforms-1.16-1.7.12
  [✔️] Powah-1.16.5-2.3.16
  [✔️] PrettyPipes-1.9.5
  [✔️] Quark-r2.4-321
  [✔️] rangedpumps-0.8.2
  [✔️] refinedstorage-1.9.15
  [✔️] refinedstorageaddons-0.7.3
  [✔️] rftoolsbase-1.16-2.1.1
  [✔️] rftoolsbuilder-1.16-3.1.4
  [✔️] rftoolspower-1.16-3.0.11
  [✔️] rftoolsstorage-1.16-2.0.15
  [✔️] rftoolsutility-1.16-3.1.7
  [✔️] rsgauges-1.16.5-1.2.13
  [✔️] rsrequestify-1.16.5-2.1.4
  [✔️] Runelic-1.16.5-7.0.2
  [✔️] selene-1.16.5-1.9.0
  [✔️] shetiphiancore-1.16-3.8.6
  [✔️] simplybackpacks-1.16.5-2.0.1-build.27
  [✔️] simplylight-1.16.5-1.4.0-build.24
  [✔️] snad-1.0.9-forge
  [✔️] storage_overhaul-1.16.5-1.0.4
  [✔️] StorageDrawers-1.16.3-8.5.0
  [✔️] supermartijn642corelib-1.0.16-mc1.16.5
  [✔️] supplementaries-1.16.5-0.18.0
  [✔️] the_vault-1.7.0p1.12.1
  [✔️] thermal_expansion-1.16.5-1.4.1.3
  [✔️] thermal_foundation-1.16.5-1.4.1.7
  [✔️] titanium-1.16.5-3.2.8.4-10
  [✔️] torchmaster-2.3.8
  [✔️] torohealth-1.16.4-forge-4
  [✔️] trashcans-1.0.11-mc1.16
  [✔️] u_team_core-1.16.5-3.2.1.196
  [✔️] useful_railroads-1.16.5-1.4.6.38
  [✔️] valkyrielib-1.16.5-3.0.9.5
  [✔️] Waddles-1.16.5-0.8.13
  [✔️] Waystones_1.16.5-7.6.4
  [✔️] Xaeros_Minimap_21.14.1_Forge_1.16.5
  [✔️] XaerosWorldMap_1.16.0_Forge_1.16.5
  [✔️] xnet-1.16-3.0.15

Params:
  --username  --version MultiMC5 --gameDir C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/instances/Vault-Hunters---Official-Modpack-1.12.2/minecraft --assetsDir C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 36.2.23 --fml.mcVersion 1.16.5 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20210115.111550

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2048m, -Xmx8192m, -Duser.language=en]

Minecraft process ID: 2104

Using onesix launcher.

Checking: MC_SLIM
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: PATCHED
Checking: MC_SRG
2022-01-19 19:09:14,312 main WARN Advanced terminal features are not available in this environment
[19:09:14] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, TonyBlock, --version, MultiMC5, --gameDir, C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/instances/Vault-Hunters---Official-Modpack-1.12.2/minecraft, --assetsDir, C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/assets, --assetIndex, 1.16, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.23, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[19:09:14] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 17.0.1 by Microsoft
[19:09:14] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[19:09:14] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/antho/Downloads/mmc-stable-win32/MultiMC/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[19:09:16] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recognition error at: '~'
[19:09:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:213]: Failed to start Minecraft:
[19:09:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: java.lang.reflect.InvocationTargetException
[19:09:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:09:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[19:09:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:09:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[19:09:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[19:09:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[19:09:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[19:09:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[19:09:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: Caused by: java.lang.reflect.InvocationTargetException
[19:09:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:09:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[19:09:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:09:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[19:09:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
[19:09:17] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	... 8 more
[19:09:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: Caused by: java.lang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
[19:09:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[19:09:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
[19:09:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[19:09:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[19:09:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[19:09:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at java.base/java.lang.Class.forName0(Native Method)
[19:09:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at java.base/java.lang.Class.forName(Class.java:467)
[19:09:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:67)
[19:09:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:70)
[19:09:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:59)
[19:09:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:196)
[19:09:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
[19:09:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
[19:09:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)
[19:09:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
[19:09:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
[19:09:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
[19:09:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[19:09:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[19:09:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[19:09:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[19:09:17] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	... 13 more
[19:09:17] [main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1
Process exited with code -1.

### Suspected cause

No idea what could be causing this issue, maybe something with the minecraft version?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by tonyblock314** [comment] 2022-01-20 00:30
uploaded version in case this helps
https://paste.ee/p/Pvvzu

**Comment by psilyntdev** [comment] 2022-01-20 02:27
I had the identical problem and error log with the exception of my version of java. I experienced the error with jre-8u321-windows-x64 build. Installing jre-8u311-windows-x64 and pointing MultiMC to that version successfully resolved the issue.

**Comment by phit** [comment] 2022-01-20 08:32
yep, forge is broken with latest java 321
Duplicate of https://github.com/MultiMC/Launcher/issues/4435

**Closed by phit** 2022-01-20 08:32 UTC
Labels: bug

**Comment by proooo10** [comment] 2022-07-10 00:06
@psilyntdev i have the exact same error
