### ISSUE TITLE
Allow offline launches when connected to a network with access restrictions

### ISSUE THREAD

**Issue by in2itivity** [MultiMC/Launcher#5129] opened 2023-04-13 01:35 UTC
### Role

My internet connection blocks access to Xbox account services.

### Suggestion

I would like offline launches not to attempt to connect to Microsoft.

### Benefit

This will improve efficiency by removing the need to enact a workaround.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

When I used the vanilla launcher for Minecraft, I found this behaviour very annoying:

* If I use the launcher without an internet connection, I can only play offline.
* If I use the launcher with an internet connection that blocks Xbox servers, I am logged out and cannot play at all, even offline. If I later disconnect my internet, it is too late&#x2014;I lost my chance.

I switched to MultiMC in hopes of not having this issue, so that I can play offline without disconnecting my internet connection first. Unfortunately, MultiMC suffers from the same issue.

I thought that <kbd>Launch Offline</kbd> would allow me to play offline even if I am connected to a network with access restrictions. Yet, MultiMC still attempts to connect to Microsoft servers, and then refuses to launch Minecraft when it fails, even though I specifically requested an offline launch. Furthermore, it then logs me out, so now I cannot play at all, even if I disconnect my internet at that point.

I believe a simple remedy would be to not attempt to contact Minecraft services when requesting to launch offline. Just because a network blocks access to said services should not mean that offline play is not possible.

Additionally, I would like to question the behaviour of logging out when a connection attempt fails: I believe that it would be more logical for MultiMC to still allow the user to play the game offline, rather than stopping both online and offline play.

**Comment by tehbasshunter** [comment] 2023-04-15 18:33
Unfortunately MMC needs to verify you actually own the game before you can even run an instance online or offline.  
  
The `Launch Offline` option is simply for those that do not have a network connection but have already verified ownership of the game and properly setup any files needed via download on first run or later.

**Comment by in2itivity** [comment] 2023-04-15 18:44
> The Launch Offline option is simply for those that do not have a network connection but have already verified ownership of the game and properly setup any files needed via download on first run or later.

Hi @tehbasshunter, I believe this is the case for me. I have already launched an instance online with MMC once while connected to a network with no restrictions. Would this constitute a valid verification, allowing me to launch on the network with restrictions at a later time?

**Comment by tehbasshunter** [comment] 2023-04-16 09:32
You're in luck.  Go to the proxy tab of MMC settings and fill all of these sections with random nonsense. It'll treat you as offline and as long as you got everything downloaded beforehand it'll work as desired.  
 
![9CHMxiq](https://user-images.githubusercontent.com/6345556/232289787-f152de91-0c06-40ed-8db3-b82b48088e0d.jpg)

**Comment by in2itivity** [comment] 2023-04-16 18:29
> Go to the proxy tab of MMC settings and fill all of these sections with random nonsense. It'll treat you as offline and as long as you got everything downloaded beforehand it'll work as desired.

Wow, @tehbasshunter, what an interesting proposal! I see why that would work, and I think that is very interesting.

I see that this issue has been changed from a suggestion to a bug, so I assume that the original behaviour has been deemed as unintentional and is slated to be changed at some point in the future. Please don't hesitate to correct me if I am mistaken.

I will stop pursuing this issue with persistence as I have now obtained a working solution and because it appears that this behaviour may be changed at some point in the future, whether that be days, weeks, months, or years down the line. Yet, I am still glad this issue is being considered, and look forward to any future updates.

**Comment by phit** [comment] 2023-05-20 07:42
Duplicate of https://github.com/MultiMC/Launcher/issues/5078

**Closed as completed by phit** 2023-05-20 07:42 UTC
Labels: bug, Auth
