### ISSUE TITLE
MultiMC asks to play with offline mode until you restart it after waking your computer from sleep mode

### ISSUE THREAD

**Issue by 4194304** [MultiMC/Launcher#5235] opened 2023-08-11 03:39 UTC
### Operating System

Windows

### Description of bug

After waking up your computer from sleep mode, it should show the correct "Fetching Username...", "Getting XBox" login process but instead it asks for offline mode until you close MultiMC and open it up again. This is incorrect since it should start the game normally, however it asks for the offline mode login which is incorrect.

### Steps to reproduce

![Screenshot 2023-08-10 203736](https://github.com/MultiMC/Launcher/assets/130800536/dab4feaf-99bf-4463-97a0-06ed3a1c05eb)
1. Put your computer to sleep
2. Click or touch the keyboard to wake the computer.
3. Log in
4. Now MultiMC should ask for an offline mode username instead of doing the usual online mode login process when launching an instance and this state should persist until MultiMC is restarted.

### Suspected cause

Hibernation memory saving?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment] 2023-08-11 09:23
Duplicate of https://github.com/MultiMC/Launcher/issues/4356

For a workaround
> manually click on the account selection, Manage Accounts, select my account and hit refresh. Only then can I launch without being prompted or having to restart MultiMC.

**Closed as completed by phit** 2023-08-11 09:23 UTC
Labels: bug, close:duplicate, Auth
