### ISSUE TITLE
Huge bugs after running for some time

### ISSUE THREAD

**Issue by andreasdc** [MultiMC/Launcher#5528] opened 2024-11-03 19:29 UTC
### Description of bug

When you run Minecraft for some time and in the logs there are gathering many messages, for example from chat (that's the possible cause), your console will open, your Minecraft can freeze and CPU usage is way higher. Closing the MultiMC process fixes that.
Related to:
https://github.com/MultiMC/Launcher/issues/5490
https://github.com/MultiMC/Launcher/issues/5513

### Steps to reproduce

1. Launch Minecraft.
2. Gather some messages on chat.
3. After some time your Minecraft can freeze, CPU usage from MultiMC will be way higher and your console will open.

### Suspected cause

A lot of chat messages sent.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment] 2024-11-10 15:29
Duplicate of https://github.com/MultiMC/Launcher/issues/5513
if you have any more information to add, please add it to that issue

**Closed as completed by phit** 2024-11-10 15:29 UTC
Labels: bug

**Comment by andreasdc** [comment] 2024-11-10 15:31
> Duplicate of #5513 if you have any more information to add, please add it to that issue

It's different issue, this one is more detailed and have more issues.
