### ISSUE TITLE
MultiMC data folder is not writable!

### ISSUE THREAD

**Issue by usamahhoosen** [MultiMC/Launcher#2004] opened 2017-09-27 16:23 UTC
When trying to launch multimc.exe i get the following message in an error dialog box

"MultiMC couldn't create a log file - the MultiMC data folder is not writable.

Make sure you have write permissions to the MultiMC data folder.

MultiMC cannot continue until you fix this problem."

**Comment by peterix** [comment] 2017-09-27 16:55
Where is MultiMC located?

Are you running it for the first time?

**Comment by usamahhoosen** [comment] 2017-09-27 17:23
This is not the first time in running MultiMC. I've used it for the past couple months successfully before I've encountered this issue. Since the issue I've tried putting MultiMC in many locations including my Desktop and Documents folder without success.

**Comment by peterix** [comment] 2017-09-27 17:53
Well, I have no idea what you did, where it was, or any of the details... but 

But basically, it cannot write into a file. That is most likely a permission problem of some sort, and no amount of moving it around will change that.
You will need to fix the permissions somehow.

Right click the MultiMC folder, then unset the read only attribute:
![image](https://user-images.githubusercontent.com/203326/30928992-75030bd2-a3bd-11e7-9e66-a58f9519553c.png)

Apply to everything.

**Comment by usamahhoosen** [comment] 2017-09-27 18:02
i have tried that as well without success.

**Comment by peterix** [comment] 2017-09-27 18:28
If you take a fresh copy downloaded from the website and put it next to the old one, does it work?

**Comment by katubug** [comment] 2017-11-27 18:47
Hi, posting for a friend. She is having the same issue. She downloaded a fresh copy from the website, and is having the same issue.

**Comment by katubug** [comment] 2017-11-27 19:13
Update: she moved it to a different folder (program files x86) and that seems to have fixed it for her.

**Comment by peterix** [comment] 2017-11-27 19:16
Hm. It definitely does not belong in any kind of 'program files'.

**Comment by peterix** [comment] 2017-11-27 19:17
So that's weird.

**Comment by Interabang33** [comment] 2017-12-16 16:56
FYSA, we had this issue when wife had unzipped the MultiMC folder to the desktop and tried to run. Followed instructions above to change folder Property setting from 'Read Only', with no effect.  Moving the folder to "C://Program Files (x86)" did work.

**Comment by nupanick** [comment] 2017-12-23 19:21
Had this problem, just solved it. You can't run things from the desktop. Moving it to your home folder or your documents folder works just fine, no need to go to program files.

**Comment by QuImUfu** [comment] 2017-12-23 23:31
Are you, by any chance using win 10 with "Controlled folder access" (basically a write protection to all user folders by default for untrusted programs) enabled? 
But that should (theoretically) give you a message when blocking MultiMC. (can not test, Windows got very crashaholic on my PC)
That should however include the documents folder.

**Comment by peterix** [comment] 2018-02-14 15:57
This is popping up every once in a while... and it is not clear what causes it.

**Comment by CursedCthulhu** [comment] 2019-08-20 11:31
Just had that problem, downloading MultiMC for the first time.
Adding MultiMC as an Authorised app to the "Controlled folder access" setting worked for me, no need to move the folder or anything.

**Comment by OrdoFlammae** [comment] 2019-08-20 13:22
@peterix, it sounds like Windows 10 has some kind of setting that keeps programs from accessing files outside certain locations (Programs (x86), etc.)

**Comment by Heufneutje** [comment] 2019-08-20 14:23
It does. It's supposed to protect against ransomware. By default it includes all of the user folders like documents, downloads, desktop and such.

**Comment by OrdoFlammae** [comment] 2019-08-22 14:22
Why is this still open? It's an issue with Windows 10, not MultiMC. It's also not fixable.

**Comment by peterix** [comment] 2019-08-22 14:27
It's a problem, it exists, it prevents people from effectively using the application, and it's confusing unless you know what's happening.

I didn't know this Windows 'feature' even existed until 2 days ago. MultiMC probably needs to detect that it is happening and tell the user to fix it.

**Comment by raould** [comment] 2020-07-08 00:48
hi, I read through all this but it is unclear to me if there's a solution for running MultiMC on Win10 from the Program Files folder. Please post a succinct explanation if there is one :-). I have been trying to set things to not be read-only for Program Files\MultiMC but it still can't write to the log file. It doesn't tell me where it is trying to write the log file other than saying "the MultiMC data folder" which doesn't actually tell me enough - where is that folder?

**Comment by peterix** [comment] 2020-07-08 08:30
It is not supported. It doesn't belong there.

**Comment by CCF100** [comment] 2020-08-06 04:59
I use Arch Linux, but my friend is also having this issue, here's a log he sent me:
[MultiMC-0.log](https://github.com/MultiMC/MultiMC5/files/5032656/MultiMC-0.log)

**Comment by Heufneutje** [comment] 2020-08-06 07:51
MultiMC is a portable application. Portable applications should not be placed in Program Files. It has nothing to do with good UX.

**Comment by Mek101** [comment] 2021-12-14 16:10
Still present on Linux. Where is the data directory multimc uses?

**Comment by OctopusET** [comment] 2021-12-14 16:13
@Mek101 I have same issue on linux.

**Comment by Mek101** [comment] 2021-12-14 16:21
If you're on Arch or derivative, multimc-bin doesn't suffer from this.

**Comment by Mek101** [comment] 2021-12-14 16:24
Btw, is seems to be caused by multimc using a subdirectory of the current directory: https://github.com/MultiMC/Launcher/blob/3c46d8a412956a759f61ae802c540ef72d00b35d/launcher/Application.cpp#L479

**Comment by Angarson** [comment] 2021-12-14 16:28
I run an update today via "http://aur.archlinux.org/packages/multimc5" on Manjaro Linux.
After the Update i recieve the following message:

The launcher couldn't create a log file - the data folder is not writable.

Make sure you have write permissions to the data folder.

The launcher cannot continue until you fix this problem.

What can i do to run MultiMC again?

Please help, thanks in advance!

**Comment by Mek101** [comment] 2021-12-14 16:44
Read exactly 2 messages above

**Comment by Angarson** [comment] 2021-12-14 17:01
Ok, that means i have to reinstall MultiMC via "https://aur.archlinux.org/packages/multimc-bin" and than it work again?

Sorry, my linux skills are not the best and english is not my native language.

**Comment by Mek101** [comment] 2021-12-14 17:05
Use your AUR helper (I use `yay`) and install the `multimc-bin` package, yes

**Comment by Angarson** [comment] 2021-12-14 17:15
Ok, i did it and it work again.

Thank you very much @Mek101 !

**Comment by peterix** [comment] 2021-12-14 17:30
This is not going to be done.

**Closed** 2021-12-14 17:30 UTC
Labels: external, usability, system: Windows

**Comment by peterix** [comment] 2021-12-14 17:32
Use the MultiMC tarball from multimc.org as intended.

**Comment by Forkk** [comment] 2021-12-14 17:32
To clarify, those saying to use the `multimc-bin` are wrong. Do not use the `multimc-bin` package or any other AUR packages for MultiMC. These will not be supported here. Use the "generic" tarball available on the website instead.

MultiMC AUR packages are not supported by upstream. Feel free to ask the maintainers of the packages for support.
