### ISSUE TITLE
Quick skin/cloak change

### ISSUE THREAD

**Issue by Frompys** [MultiMC/Launcher#5534] opened 2024-11-27 00:58 UTC
### Role

I use MultiMC as my main Launcher and would like to be able to change capes or skins in a separate menu

### Suggestion

Add a separate menu for cape and skin editing

### Benefit

It'll be much more comfortable

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I'm tired that to change the used cape in Minecraft I have to change my skin along with it or just load the same one. I propose to add a separate mini-menu in the “Profile” section to fix this shortcoming

**Comment by phit** [comment] 2024-11-27 08:10
Duplicate of https://github.com/MultiMC/Launcher/issues/3399

**Closed as completed by phit** 2024-11-27 08:10 UTC
Labels: close:duplicate
