### ISSUE TITLE
[Feature] Support Curseforge Modpack Download & Mod Downloads

### ISSUE THREAD

**Issue by AkarinLiu** [MultiMC/Launcher#5085] opened 2023-02-20 03:01 UTC
### Role

I realy need

### Suggestion

Support Curseforge Modpack Download & Mod Downloads

### Benefit

That can be handy to download mod & modpacks

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment] 2023-02-20 08:31
Duplicate of https://github.com/MultiMC/Launcher/issues/4762, https://github.com/MultiMC/Launcher/issues/4939, https://github.com/MultiMC/Launcher/issues/3057 etc

**Closed as completed by phit** 2023-02-20 08:31 UTC
Labels: close:duplicate
