### ISSUE TITLE
add an additional game arguments thing

### ISSUE THREAD

**Issue by MINECRAFTALPHAD3ATHEXE** [MultiMC/Launcher#5545] opened 2024-12-22 19:09 UTC
### Role

AlphaVer 

### Suggestion

i want an type box that says: Additional Game Arguments so you can set them

### Benefit

i need it for AlphaVer

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

![Screenshot 2024-12-22 20 07 22](https://github.com/user-attachments/assets/3876bc62-55ce-4717-a74e-8d88b88f1b7f)

**Comment by phit** [comment] 2024-12-22 19:15
Duplicate of https://github.com/MultiMC/Launcher/issues/3287

**Closed as completed by phit** 2024-12-22 19:15 UTC
