### ISSUE TITLE
Title says "Java test failed" when it succeed

### ISSUE THREAD

**Issue by CashMan3000** [MultiMC/Launcher#4589] opened 2022-03-18 21:43 UTC
### Operating System

Windows, Linux

### Description of bug

When testing the java installation in the setup, even if the java test was successful, it will say it failed.

### Steps to reproduce

Test java during setup

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment] 2022-03-18 21:45
Duplicate of https://github.com/MultiMC/Launcher/issues/4481

**Closed by phit** 2022-03-18 21:45 UTC
Labels: bug
