### ISSUE TITLE
Importing of .minecraft

### ISSUE THREAD

**Issue by Nyonyix** [MultiMC/Launcher#5164] opened 2023-05-25 02:55 UTC
### Role

Instance Creation or update

### Suggestion

Import and create or update an instance.

### Benefit

Would allow for modpack importing without any of the red tape.

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

So basically, I use linux. I have a VM where I run curseforge and download my modpacks from there, I then copy over the .minecraft folder from the VM into my native environment. Create an instance and install the required loader, Copy over the .minecraft folder to the instance folder in MultiMC and I now have a curseforge modpack in my MultiMC.

I am asking if this process can be automated on the MultiMC side, As in able to drop in the .minecraft folder and have it automatically create the instance. Or if an instance already exists, Overwrite files to 'update' the instance manually.

This would remove some of the unnecessary steps in creating or managing Curseforge modpacks within MultiMC.

How this might be achieved is by a dialog popping up when a .minecraft folder is dropped in. The dialog would specify version, name, loader, etc.

**Comment by arthomnix** [comment] 2023-05-27 17:38
In your case it would probably be easiest to use the existing FTB App Import feature, as the FTB app works on Linux and supports Curseforge packs.

**Comment by phit** [comment] 2024-12-22 21:19
Duplicate of https://github.com/MultiMC/Launcher/issues/3608
while not exactly the same vein, a bare .minecraft folder is basically meaningless

**Closed as completed by phit** 2024-12-22 21:19 UTC
Labels: suggestion

**Comment by rilakuma123** [comment] 2024-12-22 21:35
They mean the "installation directory". The saves folder, resourcepacks folder, etc. This isn't about Java. 

GDLauncher, for example, can import instances from other launchers. This is what they want.

Their suggestion of dragging a CurseForge App instance .minecraft folder may not work.
