### ISSUE TITLE
Curseforge link handler

### ISSUE THREAD

**Issue by SurmanPP** [MultiMC/Launcher#4407] opened 2022-01-05 14:26 UTC
### Role

I use curseforge for getting mods.(modpacks)

### Suggestion

Register multimc as handler for the curseforge:// links (if wanted).

### Benefit

It would allow to use the install button on the courseforge page.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment] 2022-01-05 14:33
Duplicate of https://github.com/MultiMC/Launcher/issues/3647

**Closed by phit** 2022-01-05 14:33 UTC
