### ISSUE TITLE
Can't open numerous 1.16.5 modpacks

### ISSUE THREAD

**Issue by NaruTeribery** [MultiMC/Launcher#4440] opened 2022-01-21 01:25 UTC
### Operating System

Windows

### Description of bug

I'm unable to start up most of the 1.16.5 modpacks I have installed, one of which I was just playing a few hours ago. all the modpacks were installed using the CurseForge add instance option and were known to work before. Below are logs of 4 of the modpacks I have discovered this issue with so far, with the one for Enigmatica 6 being the one I played earlier today.

Enigmatica 6: https://paste.ee/p/KD26X
Cuboid Outpost: https://paste.ee/p/uCdZM
Cave Factory: https://paste.ee/p/qRBey
Seaopolis: https://paste.ee/p/a3u53

### Steps to reproduce

*Install MultiMC
*Use CurseForge option of the "Add Instance" and select a modpack (can use Enigmatica 6 as an example)
*Try to start modpack

### Suspected cause

No sure what could be causing it personally, but I am seeing in the different logs provided above that it mentions something about 0 tokens, whatever that may mean.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment] 2022-01-21 07:47
Duplicate of https://github.com/MultiMC/Launcher/issues/4435

**Closed by phit** 2022-01-21 07:47 UTC
Labels: bug
