### ISSUE TITLE
Microsoft account status stuck at working, and cannot login 

### ISSUE THREAD

**Issue by BasicHuman103115** [MultiMC/Launcher#4322] opened 2021-12-10 03:18 UTC
### Description of bug

![Screenshot (251)](https://user-images.githubusercontent.com/83008525/145511252-210815e8-564b-4427-86ad-66ddf28c2eca.png)

I cannot use the account to play Minecraft normally as it keeps saying I am offline.
So I remove the account from Multimc then tried to add the account back, but it also stuck "Working". 

### Steps to reproduce

press Add Microsoft in Manage account.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment] 2021-12-10 08:38
Duplicate of https://github.com/MultiMC/Launcher/issues/4312

if you aren't offline please provide your MultiMC-0.log so I can tell you whats wrong on your end.

**Closed by phit** 2021-12-10 08:38 UTC
Labels: bug

**Comment by BasicHuman103115** [comment] 2021-12-10 10:21
0.008 D <> Log initialized.
    0.008 D "MultiMC 5" , (c) 2013-2021  "MultiMC Contributors"
    0.008 D Version                    :  "0.6.14-3001"
    0.008 D Git commit                 :  "80beccb2c4585260e5d170c68f72d3d303f777e0"
    0.008 D Git refspec                :  "refs/heads/stable"
    0.008 D Work dir before adjustment :  "C:/Users/user/Desktop/Games/Minecraft/MultiMC"
    0.008 D Work dir after adjustment  :  "C:/Users/user/Desktop/Games/Minecraft/MultiMC"
    0.008 D Adjusted by                :  "Fallback to binary path C:/Users/user/Desktop/Games/Minecraft/MultiMC"
    0.008 D Binary path                :  "C:/Users/user/Desktop/Games/Minecraft/MultiMC"
    0.008 D Application root path      :  "C:/Users/user/Desktop/Games/Minecraft/MultiMC"
    0.008 D <> Paths set.
    0.013 D Detected default console font: "Courier" , substitutions: ""
    0.014 D <> Settings loaded.
    0.014 D Detecting proxy settings...
    0.014 D Using no proxy is an option!
    0.014 D <> Network done.
    0.016 D Your language is "en_US"
    0.016 D <> Translations loaded.
    0.016 D Initializing updater with platform:  "win32"  --  "https://files.multimc.org/update/win32/channels.json"
    0.016 D <> Updater started.
    0.020 D Started watching  "C:/Users/user/Desktop/Games/Minecraft/MultiMC/icons"
    0.020 D Adding  "icons/TechNodefirmacraft"
    0.024 D <> Instance icons intialized.
    0.025 D <> Icon themes initialized.
    0.025 D Determining System Theme...
    0.025 D System theme seems to be: "windowsvista"
    0.025 D Considering theme from theme factory: "windows"
    0.025 D Considering theme from theme factory: "windowsxp"
    0.025 D Considering theme from theme factory: "windowsvista"
    0.025 D System theme has been determined to be: "WindowsVista"
    0.025 D Loading theme "custom"
    0.025 D <> Widget themes initialized.
    0.025 D Instance path              :  "instances"
    0.026 D Loading Instances...
    0.026 D Discovering instances in "C:/Users/user/Desktop/Games/Minecraft/MultiMC/instances"
    0.026 D Found instance ID "1.16.5 mod RAM lim"
    0.026 D Found instance ID "1.16.51"
    0.027 D Found instance ID "1.18"
    0.027 D Found instance ID "1.18 RAM lim"
    0.027 D Found instance ID "Enigmatica2Expert-1.81a1"
    0.028 D Found instance ID "Enigmatica6-0.4.10"
    0.029 D Will load group list now.
    0.029 D Group list loaded.
    0.031 D Loaded instance  "1.16.5 mod RAM lim"  from  "C:/Users/user/Desktop/Games/Minecraft/MultiMC/instances/1.16.5 mod RAM lim"
    0.031 D Loaded instance  "1.16.5 mod"  from  "C:/Users/user/Desktop/Games/Minecraft/MultiMC/instances/1.16.51"
    0.032 D Loaded instance  "1.18"  from  "C:/Users/user/Desktop/Games/Minecraft/MultiMC/instances/1.18"
    0.033 D Loaded instance  "1.18 RAM lim"  from  "C:/Users/user/Desktop/Games/Minecraft/MultiMC/instances/1.18 RAM lim"
    0.034 D Loaded instance  "Enigmatica2Expert-1.81a"  from  "C:/Users/user/Desktop/Games/Minecraft/MultiMC/instances/Enigmatica2Expert-1.81a1"
    0.035 D Loaded instance  "Enigmatica6-0.4.10"  from  "C:/Users/user/Desktop/Games/Minecraft/MultiMC/instances/Enigmatica6-0.4.10"
    0.035 D <> Instances loaded.
    0.035 D Loading accounts...
    0.035 D <> Accounts loaded.
    0.037 D <> Cache initialized.
    0.037 D Downloading Translations Index...
    0.037 D Task "NetJob(Translations Index)" starting for the first time
    0.048 D <> Icon theme set.
    0.048 D <> Application theme set.
    0.048 D <> Initialized analytics with tid "UA-87731965-2"
    0.063 W QMetaObject::connectSlotsByName: No matching signal for on_actionInstanceSettings_triggered()
    0.081 D Reloading news.
    0.081 D Task "NetJob(News RSS Feed)" starting for the first time
    0.081 D Checking for updates.
    0.081 D Channel list isn't loaded yet. Loading channel list and deferring update check.
    0.081 D Loading the channel list.
    0.081 D Task "NetJob(Update System Channel List)" starting for the first time
    0.082 D Task "NetJob(Checking for notifications)" starting for the first time
    0.126 D Viewport size "785x559"
    0.126 D RAM size is 16251 MB
    0.126 D [Analytics] "ScreenView: Main Window"
    0.126 D <> Main window shown.
    0.128 D Downloading  "https://files.multimc.org/translations/index_v2.json"
    0.583 D Downloading  "https://multimc.org/rss.xml"
    0.584 D Downloading  "https://files.multimc.org/update/win32/channels.json"
    0.586 D Downloading  "https://files.multimc.org/notifications.json"
    0.617 D Dir changed: "C:/Users/user/Desktop/Games/Minecraft/MultiMC/translations"
    3.500 D Loading the channel list.
    3.501 D Ignoring channel list update request. Already grabbing channel list.
    5.115 D Task "MSAInteractive(0x43a49b8)" starting for the first time
    5.115 D AuthFlow: "Logging in with Microsoft account."
    5.115 D DeviceFlow::link
    5.115 D DeviceFlow::setLinked: false
    7.154 W QCoreApplication::postEvent: Unexpected null receiver
   30.034 D [Analytics] "Query string = v=1&tid=UA-87731965-2&cid=48b2af7a-fd1e-4f99-bcab-d2eec77cb79b&t=screenview&ul=en-us&vp=785x559&sr=1920x1080&aip=1&cd=Main Window&an=MultiMC&av=0.6.14-3001&cd1=17.0.1&cd2=64&cd3=64&cd4=64&cd5=Windows&cd6=10.0&cm1=6272&cm2=8960&cm3=16251&qt=29908"
   36.898 D "日本語 (漢字)"
   36.942 D "日本語 (漢字)"
   90.148 D [Analytics] "Error posting message: Socket operation timed out"
   93.051 D Paged dialog close requested
   93.051 D Analytics enabled by user.
   93.053 D Detecting proxy settings...
   93.053 D Using no proxy is an option!
   93.053 D Paged dialog close approved
   93.054 D Paged dialog geometry saved
   93.065 D Discovering instances in "C:/Users/user/Desktop/Games/Minecraft/MultiMC/instances"
   93.065 D Found instance ID "1.16.5 mod RAM lim"
   93.065 D Found instance ID "1.16.51"
   93.066 D Found instance ID "1.18"
   93.066 D Found instance ID "1.18 RAM lim"
   93.066 D Found instance ID "Enigmatica2Expert-1.81a1"
   93.066 D Found instance ID "Enigmatica6-0.4.10"
   93.066 D Should keep and soft-reload "1.16.5 mod RAM lim"
   93.066 D Should keep and soft-reload "1.16.51"
   93.066 D Should keep and soft-reload "1.18"
   93.066 D Should keep and soft-reload "1.18 RAM lim"
   93.066 D Should keep and soft-reload "Enigmatica2Expert-1.81a1"
   93.066 D Should keep and soft-reload "Enigmatica6-0.4.10"
   95.618 D Loading the channel list.
   95.618 D Ignoring channel list update request. Already grabbing channel list.
  120.147 D [Analytics] "Query string = v=1&tid=UA-87731965-2&cid=48b2af7a-fd1e-4f99-bcab-d2eec77cb79b&t=screenview&ul=en-us&vp=785x559&sr=1920x1080&aip=1&cd=Main Window&an=MultiMC&av=0.6.14-3001&cd1=17.0.1&cd2=64&cd3=64&cd4=64&cd5=Windows&cd6=10.0&cm1=6272&cm2=8960&cm3=16251&qt=120021"
  120.757 C Failed  "https://files.multimc.org/translations/index_v2.json"  with reason  QNetworkReply::NetworkError(TimeoutError)
  120.757 D Download failed in previous step: "https://files.multimc.org/translations/index_v2.json"
  120.758 D Downloading  "https://files.multimc.org/translations/index_v2.json"
  120.758 C Failed  "https://files.multimc.org/update/win32/channels.json"  with reason  QNetworkReply::NetworkError(TimeoutError)
  120.758 D Download failed in previous step: "https://files.multimc.org/update/win32/channels.json"
  120.758 D Downloading  "https://files.multimc.org/update/win32/channels.json"
  120.758 C Failed  "https://files.multimc.org/notifications.json"  with reason  QNetworkReply::NetworkError(TimeoutError)
  120.758 D Download failed in previous step: "https://files.multimc.org/notifications.json"
  120.760 D Downloading  "https://files.multimc.org/notifications.json"
  120.762 C Failed  "https://multimc.org/rss.xml"  with reason  QNetworkReply::NetworkError(TimeoutError)
  120.762 D Download failed in previous step: "https://multimc.org/rss.xml"
  120.762 D Downloading  "https://multimc.org/rss.xml"
  120.762 D Dir changed: "C:/Users/user/Desktop/Games/Minecraft/MultiMC/translations"
  120.769 D "日本語 (漢字)"
  120.769 D "日本語 (漢字)"
  120.773 D Dir changed: "C:/Users/user/Desktop/Games/Minecraft/MultiMC/translations"
  120.775 D "日本語 (漢字)"
  124.951 D Paged dialog close requested
  124.951 D Analytics enabled by user.
  124.951 D Detecting proxy settings...
  124.951 D Using no proxy is an option!
  124.951 D Paged dialog close approved
  124.951 D Paged dialog geometry saved
  124.960 D Discovering instances in "C:/Users/user/Desktop/Games/Minecraft/MultiMC/instances"
  124.960 D Found instance ID "1.16.5 mod RAM lim"
  124.960 D Found instance ID "1.16.51"
  124.960 D Found instance ID "1.18"
  124.960 D Found instance ID "1.18 RAM lim"
  124.961 D Found instance ID "Enigmatica2Expert-1.81a1"
  124.961 D Found instance ID "Enigmatica6-0.4.10"
  124.961 D Should keep and soft-reload "1.16.5 mod RAM lim"
  124.961 D Should keep and soft-reload "1.16.51"
  124.961 D Should keep and soft-reload "1.18"
  124.961 D Should keep and soft-reload "1.18 RAM lim"
  124.961 D Should keep and soft-reload "Enigmatica2Expert-1.81a1"
  124.961 D Should keep and soft-reload "Enigmatica6-0.4.10"
  127.514 D Loading the channel list.
  127.514 D Ignoring channel list update request. Already grabbing channel list.
  164.571 D Paged dialog close requested
  164.571 D Analytics enabled by user.
  164.571 D Detecting proxy settings...
  164.571 D Using no proxy is an option!
  164.571 D Paged dialog close approved
  164.571 D Paged dialog geometry saved
  164.581 D Discovering instances in "C:/Users/user/Desktop/Games/Minecraft/MultiMC/instances"
  164.581 D Found instance ID "1.16.5 mod RAM lim"
  164.582 D Found instance ID "1.16.51"
  164.582 D Found instance ID "1.18"
  164.582 D Found instance ID "1.18 RAM lim"
  164.582 D Found instance ID "Enigmatica2Expert-1.81a1"
  164.582 D Found instance ID "Enigmatica6-0.4.10"
  164.582 D Should keep and soft-reload "1.16.5 mod RAM lim"
  164.582 D Should keep and soft-reload "1.16.51"
  164.582 D Should keep and soft-reload "1.18"
  164.582 D Should keep and soft-reload "1.18 RAM lim"
  164.582 D Should keep and soft-reload "Enigmatica2Expert-1.81a1"
  164.582 D Should keep and soft-reload "Enigmatica6-0.4.10"
  171.169 D Task "ComponentUpdateTask(0x6a80e08)" starting for the first time
  171.169 D Loading components
  171.171 D Task "NetJob(Download of meta file index.json)" starting for the first time
  171.171 D Remote loading is being run for metadata index
  171.173 D Task "NetJob(Download of meta file org.lwjgl3/3.2.2.json)" starting for the first time
  171.173 D Remote loading is being run for "LWJGL 3"
  171.175 D Task "NetJob(Download of meta file net.minecraft/1.18.json)" starting for the first time
  171.175 D Remote loading is being run for "Minecraft"
  171.176 D Task "NetJob(Download of meta file net.fabricmc.intermediary/1.18.json)" starting for the first time
  171.176 D Remote loading is being run for "Intermediary Mappings"
  171.177 D Task "NetJob(Download of meta file net.fabricmc.fabric-loader/0.12.8.json)" starting for the first time
  171.177 D Remote loading is being run for "Fabric Loader"
  171.179 D Task "NetJob(Download of meta file org.lwjgl3/index.json)" starting for the first time
  171.180 W QMetaObject::connectSlotsByName: No matching signal for on_RunningState_changed(bool)
  171.182 W QMetaObject::connectSlotsByName: No matching signal for on_RunningState_changed(bool)
  171.184 W QMetaObject::connectSlotsByName: No matching signal for on_RunningState_changed(bool)
  171.186 W QMetaObject::connectSlotsByName: No matching signal for on_RunningState_changed(bool)
  171.188 W QMetaObject::connectSlotsByName: No matching signal for on_RunningState_changed(bool)
  171.190 W QMetaObject::connectSlotsByName: No matching signal for on_RunningState_changed(bool)
  171.417 D Applying "org.lwjgl3" GOOD
  171.417 D Applying "net.minecraft" GOOD
  171.417 D Applying "net.fabricmc.intermediary" GOOD
  171.417 D Applying "net.fabricmc.fabric-loader" GOOD
  171.471 D Downloading  "https://meta.multimc.org/v1/index.json"
  171.472 D Downloading  "https://meta.multimc.org/v1/org.lwjgl3/3.2.2.json"
  171.473 D Downloading  "https://meta.multimc.org/v1/net.minecraft/1.18.json"
  171.474 D Downloading  "https://meta.multimc.org/v1/net.fabricmc.intermediary/1.18.json"
  171.475 D Downloading  "https://meta.multimc.org/v1/net.fabricmc.fabric-loader/0.12.8.json"
  171.476 D Downloading  "https://meta.multimc.org/v1/org.lwjgl3/index.json"
  180.146 D [Analytics] "Error posting message: Socket operation timed out"
  188.810 W QFileSystemWatcher::removePaths: list is empty
  210.144 D [Analytics] "Query string = v=1&tid=UA-87731965-2&cid=48b2af7a-fd1e-4f99-bcab-d2eec77cb79b&t=screenview&ul=en-us&vp=785x559&sr=1920x1080&aip=1&cd=Main Window&an=MultiMC&av=0.6.14-3001&cd1=17.0.1&cd2=64&cd3=64&cd4=64&cd5=Windows&cd6=10.0&cm1=6272&cm2=8960&cm3=16251&qt=210018"
  235.247 D Loading the channel list.
  235.247 D Ignoring channel list update request. Already grabbing channel list.
  239.279 D Task "MSAInteractive(0x6b9b318)" starting for the first time
  239.279 D AuthFlow: "Logging in with Microsoft account."
  239.279 D DeviceFlow::link
  239.279 D DeviceFlow::setLinked: false
  240.755 C Failed  "https://files.multimc.org/translations/index_v2.json"  with reason  QNetworkReply::NetworkError(TimeoutError)
  240.755 D Download failed in previous step: "https://files.multimc.org/translations/index_v2.json"
  240.756 D Downloading  "https://files.multimc.org/translations/index_v2.json"
  240.756 C Failed  "https://files.multimc.org/update/win32/channels.json"  with reason  QNetworkReply::NetworkError(TimeoutError)
  240.756 D Download failed in previous step: "https://files.multimc.org/update/win32/channels.json"
  240.756 D Downloading  "https://files.multimc.org/update/win32/channels.json"
  240.756 C Failed  "https://files.multimc.org/notifications.json"  with reason  QNetworkReply::NetworkError(TimeoutError)
  240.756 D Download failed in previous step: "https://files.multimc.org/notifications.json"
  240.757 D Downloading  "https://files.multimc.org/notifications.json"
  240.757 C Failed  "https://multimc.org/rss.xml"  with reason  QNetworkReply::NetworkError(TimeoutError)
  240.757 D Download failed in previous step: "https://multimc.org/rss.xml"
  240.757 D Downloading  "https://multimc.org/rss.xml"
  240.757 D Dir changed: "C:/Users/user/Desktop/Games/Minecraft/MultiMC/translations"
  240.763 D "日本語 (漢字)"
  240.763 D "日本語 (漢字)"
  240.767 D Dir changed: "C:/Users/user/Desktop/Games/Minecraft/MultiMC/translations"
  240.769 D "日本語 (漢字)"
  270.144 D [Analytics] "Error posting message: Socket operation timed out"
  291.584 C Failed  "https://meta.multimc.org/v1/index.json"  with reason  QNetworkReply::NetworkError(TimeoutError)
  291.584 D Download failed in previous step: "https://meta.multimc.org/v1/index.json"
  291.585 D Downloading  "https://meta.multimc.org/v1/index.json"
  291.585 C Failed  "https://meta.multimc.org/v1/org.lwjgl3/3.2.2.json"  with reason  QNetworkReply::NetworkError(TimeoutError)
  291.585 D Download failed in previous step: "https://meta.multimc.org/v1/org.lwjgl3/3.2.2.json"
  291.586 D Downloading  "https://meta.multimc.org/v1/org.lwjgl3/3.2.2.json"
  291.586 C Failed  "https://meta.multimc.org/v1/net.minecraft/1.18.json"  with reason  QNetworkReply::NetworkError(TimeoutError)
  291.586 D Download failed in previous step: "https://meta.multimc.org/v1/net.minecraft/1.18.json"
  291.587 D Downloading  "https://meta.multimc.org/v1/net.minecraft/1.18.json"
  291.587 C Failed  "https://meta.multimc.org/v1/net.fabricmc.intermediary/1.18.json"  with reason  QNetworkReply::NetworkError(TimeoutError)
  291.587 D Download failed in previous step: "https://meta.multimc.org/v1/net.fabricmc.intermediary/1.18.json"
  291.588 D Downloading  "https://meta.multimc.org/v1/net.fabricmc.intermediary/1.18.json"
  291.588 C Failed  "https://meta.multimc.org/v1/net.fabricmc.fabric-loader/0.12.8.json"  with reason  QNetworkReply::NetworkError(TimeoutError)
  291.588 D Download failed in previous step: "https://meta.multimc.org/v1/net.fabricmc.fabric-loader/0.12.8.json"
  291.589 D Downloading  "https://meta.multimc.org/v1/net.fabricmc.fabric-loader/0.12.8.json"
  291.589 C Failed  "https://meta.multimc.org/v1/org.lwjgl3/index.json"  with reason  QNetworkReply::NetworkError(TimeoutError)
  291.589 D Download failed in previous step: "https://meta.multimc.org/v1/org.lwjgl3/index.json"
  291.590 D Downloading  "https://meta.multimc.org/v1/org.lwjgl3/index.json"
  291.599 C Failed  "https://meta.multimc.org/v1/index.json"  with reason  QNetworkReply::NetworkError(TimeoutError)
  291.599 D Download failed in previous step: "https://meta.multimc.org/v1/index.json"
  291.600 D Downloading  "https://meta.multimc.org/v1/index.json"
  291.600 C Failed  "https://meta.multimc.org/v1/org.lwjgl3/3.2.2.json"  with reason  QNetworkReply::NetworkError(TimeoutError)
  291.600 D Download failed in previous step: "https://meta.multimc.org/v1/org.lwjgl3/3.2.2.json"
  291.601 D Downloading  "https://meta.multimc.org/v1/org.lwjgl3/3.2.2.json"
  291.601 C Failed  "https://meta.multimc.org/v1/net.minecraft/1.18.json"  with reason  QNetworkReply::NetworkError(TimeoutError)
  291.601 D Download failed in previous step: "https://meta.multimc.org/v1/net.minecraft/1.18.json"
  291.602 D Downloading  "https://meta.multimc.org/v1/net.minecraft/1.18.json"
  291.602 C Failed  "https://meta.multimc.org/v1/net.fabricmc.intermediary/1.18.json"  with reason  QNetworkReply::NetworkError(TimeoutError)
  291.602 D Download failed in previous step: "https://meta.multimc.org/v1/net.fabricmc.intermediary/1.18.json"
  291.603 D Downloading  "https://meta.multimc.org/v1/net.fabricmc.intermediary/1.18.json"
  291.603 C Failed  "https://meta.multimc.org/v1/net.fabricmc.fabric-loader/0.12.8.json"  with reason  QNetworkReply::NetworkError(TimeoutError)
  291.603 D Download failed in previous step: "https://meta.multimc.org/v1/net.fabricmc.fabric-loader/0.12.8.json"
  291.603 D Downloading  "https://meta.multimc.org/v1/net.fabricmc.fabric-loader/0.12.8.json"
  291.604 C Failed  "https://meta.multimc.org/v1/org.lwjgl3/index.json"  with reason  QNetworkReply::NetworkError(TimeoutError)
  291.604 D Download failed in previous step: "https://meta.multimc.org/v1/org.lwjgl3/index.json"
  291.604 D Downloading  "https://meta.multimc.org/v1/org.lwjgl3/index.json"
  300.144 D [Analytics] "Query string = v=1&tid=UA-87731965-2&cid=48b2af7a-fd1e-4f99-bcab-d2eec77cb79b&t=screenview&ul=en-us&vp=785x559&sr=1920x1080&aip=1&cd=Main Window&an=MultiMC&av=0.6.14-3001&cd1=17.0.1&cd2=64&cd3=64&cd4=64&cd5=Windows&cd6=10.0&cm1=6272&cm2=8960&cm3=16251&qt=300018"
  303.253 W QCoreApplication::postEvent: Unexpected null receiver
  303.875 D Paged dialog close requested
  303.875 D Analytics enabled by user.
  303.875 D Detecting proxy settings...
  303.876 D Using no proxy is an option!
  303.876 D Paged dialog close approved
  303.876 D Paged dialog geometry saved
  303.883 D Discovering instances in "C:/Users/user/Desktop/Games/Minecraft/MultiMC/instances"
  303.883 D Found instance ID "1.16.5 mod RAM lim"
  303.883 D Found instance ID "1.16.51"
  303.883 D Found instance ID "1.18"
  303.883 D Found instance ID "1.18 RAM lim"
  303.883 D Found instance ID "Enigmatica2Expert-1.81a1"
  303.884 D Found instance ID "Enigmatica6-0.4.10"
  303.884 D Should keep and soft-reload "1.16.5 mod RAM lim"
  303.884 D Should keep and soft-reload "1.16.51"
  303.884 D Should keep and soft-reload "1.18"
  303.884 D Should keep and soft-reload "1.18 RAM lim"
  303.884 D Should keep and soft-reload "Enigmatica2Expert-1.81a1"
  303.884 D Should keep and soft-reload "Enigmatica6-0.4.10"
  317.510 D Loading the channel list.
  317.511 D Ignoring channel list update request. Already grabbing channel list.
  319.615 D Task "MSAInteractive(0x6b9d098)" starting for the first time
  319.615 D AuthFlow: "Logging in with Microsoft account."
  319.615 D DeviceFlow::link
  319.615 D DeviceFlow::setLinked: false
  360.144 D [Analytics] "Error posting message: Socket operation timed out"
  360.756 C Failed  "https://files.multimc.org/translations/index_v2.json"  with reason  QNetworkReply::NetworkError(TimeoutError)
  360.756 D Download failed in previous step: "https://files.multimc.org/translations/index_v2.json"
  360.757 D Downloading  "https://files.multimc.org/translations/index_v2.json"
  360.757 C Failed  "https://files.multimc.org/update/win32/channels.json"  with reason  QNetworkReply::NetworkError(TimeoutError)
  360.757 D Download failed in previous step: "https://files.multimc.org/update/win32/channels.json"
  360.757 D Downloading  "https://files.multimc.org/update/win32/channels.json"
  360.757 C Failed  "https://files.multimc.org/notifications.json"  with reason  QNetworkReply::NetworkError(TimeoutError)
  360.757 D Download failed in previous step: "https://files.multimc.org/notifications.json"
  360.758 D Downloading  "https://files.multimc.org/notifications.json"
  360.758 C Failed  "https://multimc.org/rss.xml"  with reason  QNetworkReply::NetworkError(TimeoutError)
  360.758 D Download failed in previous step: "https://multimc.org/rss.xml"
  360.758 D Downloading  "https://multimc.org/rss.xml"
  360.758 D Dir changed: "C:/Users/user/Desktop/Games/Minecraft/MultiMC/translations"
  360.765 D "日本語 (漢字)"
  360.765 D "日本語 (漢字)"
  360.769 D Dir changed: "C:/Users/user/Desktop/Games/Minecraft/MultiMC/translations"
  360.772 D "日本語 (漢字)"
  388.644 W QCoreApplication::postEvent: Unexpected null receiver
  390.143 D [Analytics] "Query string = v=1&tid=UA-87731965-2&cid=48b2af7a-fd1e-4f99-bcab-d2eec77cb79b&t=screenview&ul=en-us&vp=785x559&sr=1920x1080&aip=1&cd=Main Window&an=MultiMC&av=0.6.14-3001&cd1=17.0.1&cd2=64&cd3=64&cd4=64&cd5=Windows&cd6=10.0&cm1=6272&cm2=8960&cm3=16251&qt=390017"

**Comment by BasicHuman103115** [comment] 2021-12-10 10:22
[MultiMC-0.log](https://github.com/MultiMC/Launcher/files/7691966/MultiMC-0.log)

**Comment by phit** [comment] 2021-12-10 11:29
looks like you are completely offline, any antivirus, network filtering, public wifi or similar that could cause this?

**Comment by BasicHuman103115** [comment] 2021-12-10 11:39
ok, i will take a look at those
but before I update mmc to the latest version today
it works perfectly fine

**Comment by Wooty-B** [comment] 2022-06-19 20:30
I am having this same issue after an update via pi-apps. I tried manually building latest version and issue persists, no online functionality at all. It appears to be ssl related? I am using hardwired LAN/everything else is online, running on an ARM64 workstation (LX2K), Debian 11 Kernel 5.15
[DevLauncher-0.log](https://github.com/MultiMC/Launcher/files/8936341/DevLauncher-0.log)

**Comment by phit** [comment] 2022-06-19 20:50
your certificate store is broken and or is missing the required certificates, please don't use other peoples completely unrelated issues for support

**Comment by JeremyStarTM** [comment] 2022-07-18 23:04
I also have problems with the MSA login on my Raspberry Pi 4B running Manjaro. Here's my log: [MultiMC-1.log](https://github.com/MultiMC/Launcher/files/9136166/MultiMC-1.log)

**Comment by jgonyea** [comment] 2022-10-15 22:13
I'm experiencing the same issue.  Log at https://pastebin.com/4RFr34kC

Relevant logs:
```
  278.816 D Group list saved.
  278.817 D Task "InstanceStaging(0xaaaaf60b76a0)" succeeded
  283.043 D Task "MSAInteractive(0xaaaaf65babc0)" starting for the first time
  283.044 D AuthFlow: "Logging in with Microsoft account."
  283.045 D DeviceFlow::link
  283.046 D DeviceFlow::setLinked: false
  287.373 D DeviceFlow::onDeviceAuthReplyFinished

```
