### ISSUE TITLE
Can't close startup window when Mojang authentication services unavailable

### ISSUE THREAD

**Issue by Motifier** [MultiMC/Launcher#4434] opened 2022-01-18 10:44 UTC
### Operating System

Windows

### Description of bug

When attempting to launch an instance with Mojang authentication services unavailable MultiMC just loops and doesn't allow the user to close the window shown here (clicking the X in the top corner does not allow you to close the window)
![image](https://user-images.githubusercontent.com/11881520/149921236-3858c930-7964-4456-8c18-7ef032375db7.png)

Before I restarted my instance I was receiving this issue when attempting to log back into the server I had just left "Failed to log in: The authentication servers are currently not reachable. Please try again."

### Steps to reproduce

- When Mojang authentication services are unavailable

1. Open MultiMC
2. Select Instance
3. Launch
4. MultiMC will continually loop and not allow the user to close this window:
![image](https://user-images.githubusercontent.com/11881520/149921997-b0a1df52-94bd-49ec-a426-f9d527b1a872.png)
5. Force close the window with Task Manager

### Suspected cause

Mojang authentication services unavailable, preventing instance from launching.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Motifier** [comment] 2022-01-18 10:51
Authentication servers appear to be back up and running and thus not an issue anymore starting MultiMC, not sure if worth fixing this 'issue' if authentication servers have a 99%+ uptime

**Comment by phit** [comment] 2022-01-18 11:52
Duplicate of https://github.com/MultiMC/Launcher/issues/4433

**Closed by phit** 2022-01-18 11:52 UTC
Labels: bug
