### ISSUE TITLE
[Suggestion] Display curently installed modpack version

### ISSUE THREAD

**Issue by Srdjan-V** [MultiMC/Launcher#4579] opened 2022-03-14 15:39 UTC
### Role

I play modded minecraft.

### Suggestion

Simply display the version of the modpack in the name by default.

### Benefit

Its a simple QOL feature.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### I don't mind updating the modpack manually but not knowing what the current version is a major downside.

![image](https://user-images.githubusercontent.com/78452357/158205041-2cb345b3-c6c7-4c8c-96a1-b0d24324a4a9.png)

### Adding a check box here, to add the version string at the end wood be possible. 

![image](https://user-images.githubusercontent.com/78452357/158205770-5ca99a32-3269-4415-ac06-5debd6637614.png)

**Comment by phit** [comment] 2022-03-14 17:43
Duplicate of https://github.com/MultiMC/Launcher/issues/3769

the problem is there is no clean name provided to use for this with CurseForge, other platforms already do this

**Closed by phit** 2022-03-14 17:43 UTC
