### ISSUE TITLE
Add a skin manager!

### ISSUE THREAD

**Issue by MrMcyeet** [MultiMC/Launcher#4388] opened 2021-12-26 07:15 UTC
### Role

I play in a veriety of different servers, some RP, which require the use of different skins.

### Suggestion

I want MultiMC to have a skins tab just below the accounts tab that has the option to have multiple skins saved locally, which can be previewed, and it should include a button to upload it to mojang and set it as your current active skin

### Benefit

Not only would this make switching skins much easier, it would allow you to preview skins before you upload/use them. This would allow more creativity as players arent super familliar with how to switch skins could easily download or make a skin, and use MultiMC to manage it

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

That is pretty much the idea, It would be super useful to have a tab like that, and would allow you to change your skin based on what you were doing, or what kind of mood you are in.

**Comment by xag803** [comment] 2021-12-26 16:29
This would be cool. It would be useful if they added a editor as well.

**Comment by phit** [comment] 2021-12-28 08:54
Duplicate of https://github.com/MultiMC/Launcher/issues/3399

**Closed by phit** 2021-12-28 08:54 UTC
