### ISSUE TITLE
Unable to install RLCraft 2.9.3 on Linux (Failed to extract modpack)

### ISSUE THREAD

**Issue by MangyCat** [MultiMC/Launcher#5311] opened 2023-12-16 18:23 UTC
### Operating System

Linux

### Description of bug

I expected everything to extract fine and for the RLCraft modpack to install and extract.
However it failed and showed me failed to extract modpack, so i go to my terminal and i see 

4949.791 W Failed to extract file "mods/CraftTweaker2-1.12-4.1.20.687.jar" to "/home/etore/.local/share/multimc/instances/_LAUNCHER_TEMP/{e6de9072-1699-48a2-bc8f-d9183b4697c2}/.minecraft/mods/CraftTweaker2-1.12-4.1.20.687.jar"
 4949.792 C Task "Technic::SingleZipPackInstallTask(0x14d2900)" failed:  "Failed to extract modpack"
 4949.848 C Task "InstanceStaging(0x7fe2840092c0)" failed:  "Failed to extract modpack"

### Steps to reproduce

* Go to add instance
* Click on technic 
* go to rlcraft
* download rlcraft version 2.9.3
* wait for it to download
* see error

### Suspected cause

I think that the problem is caused by the Crafttweaker2 jar file having issues with extracting, so maybe error in archive? Or its technic's fault and not neccessarily multimc's fault?
![Screenshot_2023-12-16_19-19-51](https://github.com/MultiMC/Launcher/assets/73955445/583827f4-e2f1-4294-9bef-558fed2926d0)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment] 2023-12-16 19:21
Duplicate of https://github.com/MultiMC/Launcher/issues/4182

**Comment by phit** [comment] 2023-12-16 19:23
actually no, this modpack is just broken 7zip can't extract that file either, report it to the modpack author
![image](https://github.com/MultiMC/Launcher/assets/2097483/677595f5-a696-4a9c-994f-8c226c86ffbf)

**Closed as completed by phit** 2023-12-16 19:23 UTC
Labels: external
