### ISSUE TITLE
Allow setting accounts to instances 

### ISSUE THREAD

**Issue by TomLewis** [MultiMC/Launcher#4805] opened 2022-07-02 10:00 UTC
### Role

I run a minecraft server and have 2 accounts for testing plugins

### Suggestion

Bind an account to an instance, so I can just play and not have to swtich accounts first

### Benefit

Better UX, Quality of life, not requring mulitple selections for a basic task

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

A lot of server owners have multiple accounts to test as a player as well as owner of a server at the same time, we need a quick way to open another instance, without having to first select the other account.
I am ALWAYS forgetting to select the second account before opening my second instance.

**Comment by phit** [comment] 2022-07-02 10:01
Duplicate of https://github.com/MultiMC/Launcher/issues/3116

**Closed by phit** 2022-07-02 10:01 UTC

**Comment by phit** [comment] 2022-07-02 10:02
also as somewhat of a workaround to your issue, if you don't set a default account it will ask you what account to use before launching
