### ISSUE TITLE
While installing a modpack, a failure resolving mod IDs provides no info/log about which mod ID was the culprit.

### ISSUE THREAD

**Issue by anpilley** [MultiMC/Launcher#1977] opened 2017-09-03 02:15 UTC
System Information
-----------------------------
MultiMC version: 0.6.0-develop-1061 

Operating System: win10 (1703)

Summary of the issue or suggestion:
----------------------------------------------
Trying to add the Modern Skyblock modpack (2.3.8). Fails to resolve mod IDs with an error dialog:
"Unable to resolve mod IDs:
Some mod ID resolving tasks failed"

However, MultiMC doesn't provide any kind of log or the ID of the mod that can't be found for debugging purposes.

(Note, Modern skyblock 2.4.x works okay, there was legitimately a missing mod in older versions, but MultiMC doesn't provide useful debugging info to figure out what's wrong and try to fix it)

What should happen:
------------------------------
MultiMC should provide the ID(s) of the mods that couldn't be resolved.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Get Modern Skyblock 2.3.8 from here: https://mods.curse.com/modpacks/minecraft/258228-modern-skyblock-2#t1:other-downloads

2. Attempt to add the modpack zip

3. Watch as MultiMC fails but doesn't say which mod ID failed.

Suspected cause:
---------------------------
Need some more info in the error dialog.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by qurben** [comment] 2018-02-25 19:25
Running MultiMC from the console provides some more debug info.

I ran into a similar issue with Modern Skyblock 3.1.5.1 where the page https://cursemeta.dries007.net/228525/2534543.json and https://cursemeta.dries007.net/281791/2534481.json wouldn't return proper JSON. (it contained [this](https://paste.ee/p/zjuT9))

So it's probably an error caused by curseMeta.

**Comment by dries007** [comment] 2018-02-25 21:55
I'm looking into this, see dries007/curseMeta#7.

**Comment by stephen-smith** [comment] 2018-03-25 02:56
Having same issue on https://www.feed-the-beast.com/projects/ftb-pyramid-reborn/files/2542764 and https://minecraft.curseforge.com/projects/modern-skyblock-3-departed/files/2536753

**Comment by stephen-smith** [comment] 2018-03-25 03:36
Upgrading to the development stream and dealing with #1816 resulted in successful downloads for me.

**Comment by JorgenHedlund** [comment] 2018-10-13 08:49
(more of a FYI)

Seeing this issue today, with Modern Skyblock-3.4.2 https://minecraft.curseforge.com/projects/modern-skyblock-3-departed/files/2607165 

>    18.932 C Failed  "https://cursemeta.dries007.net/262691/2450585.json"  with reason  QNetworkReply::NetworkError(InternalServerError)
   18.932 D Download failed in previous step: "https://cursemeta.dries007.net/262691/2450585.json"
   18.932 D Downloading  "https://cursemeta.dries007.net/262691/2450585.json"
   19.531 C Failed  "https://cursemeta.dries007.net/262691/2450585.json"  with reason  QNetworkReply::NetworkError(InternalServerError)
   19.531 D Download failed in previous step: "https://cursemeta.dries007.net/262691/2450585.json"
   19.532 D Downloading  "https://cursemeta.dries007.net/262691/2450585.json"
   20.257 C Failed  "https://cursemeta.dries007.net/262691/2450585.json"  with reason  QNetworkReply::NetworkError(InternalServerError)
   20.258 D Download failed in previous step: "https://cursemeta.dries007.net/262691/2450585.json"
   20.258 D Downloading  "https://cursemeta.dries007.net/262691/2450585.json"
   20.925 C Failed  "https://cursemeta.dries007.net/262691/2450585.json"  with reason  QNetworkReply::NetworkError(InternalServerError)
   20.925 D Download failed in previous step: "https://cursemeta.dries007.net/262691/2450585.json"
   20.926 C Task "NetJob(Mod id resolver)" failed:  "Job 'Mod id resolver' failed to process:\nhttps://cursemeta.dries007.net/262691/2450585.json"
   20.935 C Exception: "Document: Error parsing JSON: illegal value"
   20.935 C Resolving of 262691 2450585 failed because of a parsing error:
   20.935 C "Document: Error parsing JSON: illegal value"
   20.935 C JSON:
   20.935 C ""

From modlist.html:
> <li><a href="https://minecraft.curseforge.com/mc-mods/262691">ExU2 - Cursed Earth Ritual (by voxatu)</a></li>
... which has a 404.
My conclusion is that this is on Curse's side. Mod deleted or whatever. Search engine shows it https://duckduckgo.com/?q=ExU2+-+Cursed+Earth+Ritual+(by+voxatu)

**Comment by dries007** [comment] 2018-10-13 08:52
Yes, and there is no graceful way of catching this, since the API just pretends it doesn't exist.
Maybe at some point I can hook to API into the database so it can give a relevant error message on deleted projects.

**Comment by phit** [comment] 2022-05-19 20:46
Curseforge integration has been removed with https://github.com/MultiMC/Launcher/commit/0a827ba70e6ef20187f8507a536d54a8441020dc

**Closed by phit** 2022-05-19 20:46 UTC
Labels: bug, usability

**Comment by Mambasaur** [comment] 2022-06-05 03:12
I had the same happen, running multiMC 5 on Windows 10 64x pro.
![Screenshot 2022-06-05 105935](https://user-images.githubusercontent.com/106896514/172033352-a6b7641f-9f49-4ad7-873e-934dfcb812c9.png)

**Comment by musznik** [comment] 2022-06-07 18:00
> I had the same happen, running multiMC 5 on Windows 10 64x pro. ![Screenshot 2022-06-05 105935](https://user-images.githubusercontent.com/106896514/172033352-a6b7641f-9f49-4ad7-873e-934dfcb812c9.png)

better read this... https://www.reddit.com/r/feedthebeast/comments/utah7j/multimc_to_remove_ftb_and_curse_integration/

**Comment by Luke112211** [comment] 2022-06-09 17:45
Have the same preoblem / error.
Is there a solution for this?
I have no idea what i can do :(

**Comment by musznik** [comment] 2022-06-09 18:00
> Have the same preoblem / error. Is there a solution for this? I have no idea what i can do :(

1. use PolyMC
2. **or** manually copy all files from CurseForge (install vanilla mc, select version, add forge/fabric, copy all files from CF client)
3. **or** copy all mods manually

No better solution so far, slowpoke just loving all of us so much..

**Comment by Luke112211** [comment] 2022-06-09 19:37
Okay thank,

so i did it, but i habe a new problem.
Can you help me again? 
![Uploading image.jpg…]()

**Comment by peterix** [comment] 2022-06-09 19:40
This is no place for advertising.

**Comment by peterix** [comment] 2022-06-09 19:41
And this issue is no longer relevant, because this funcionality has been removed entirely.
