### ISSUE TITLE
Command Line Launch offline? 

### ISSUE THREAD

**Issue by Geagg427** [MultiMC/Launcher#4501] opened 2022-02-10 00:56 UTC
### Role

I am trying to make a shortcut for my game launcher.

### Suggestion

Add a new launch option to launch the instance offline immediately.

### Benefit

So that its possible to launch directly offline from a script/command line.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment] 2022-02-10 13:35
Duplicate of https://github.com/MultiMC/Launcher/issues/3012
lease use the search before opening new issues

**Closed by phit** 2022-02-10 13:35 UTC
