### ISSUE TITLE
Add option to close on minecraft launch

### ISSUE THREAD

**Issue by andreasdc** [MultiMC/Launcher#5054] opened 2023-02-05 07:55 UTC
### Role

-

### Suggestion

-

### Benefit

-

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

You could add option to close the launcher on minecraft launch, it will make things easier.

**Comment by phit** [comment] 2023-02-05 10:11
Duplicate of https://github.com/MultiMC/Launcher/issues/3406

**Closed as not planned by phit** 2023-02-05 10:11 UTC
Labels: close:duplicate, suggestion
