### ISSUE TITLE
Forge Library error

### ISSUE THREAD

**Issue by RUKVI** [MultiMC/Launcher#5355] opened 2024-02-28 23:16 UTC
### Operating System

Windows

### Description of bug

https://paste.ee/p/ipQ2R
constantly get this error when i try to run minecraft with forge
looked at the library folder and nothing is there

### Steps to reproduce

Edit instance > install stable version (starred) of forge (also happened with other versions) > launch

### Suspected cause

forge is definitely not able to retrieve something from library for whatever reason but i dont have enough computer knowledge to guess

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment] 2024-02-28 23:17
Duplicate of https://github.com/MultiMC/Launcher/issues/5353

**Closed as completed by phit** 2024-02-28 23:17 UTC
Labels: bug
