### ISSUE TITLE
List update failed due to TLS certificate problem

### ISSUE THREAD

**Issue by markuspi** [MultiMC/Launcher#4959] opened 2022-10-30 12:24 UTC
### Operating System

Linux

### Description of bug

MultiMC is unable to download the list of available versions:

```
List update failed:
Job 'Download of meta file net.minecraft/index.json' failed to process:
https://meta.multimc.org/v1/net.minecraft/index.json
```

### Steps to reproduce

* Click Add Instance
* Click Refresh
* Error message shows up

### Suspected cause

The [logfile](https://gist.github.com/markuspi/8de75fd9b522abb29b151670634cf889) indicates that there is an issue with the SSL/TLS certificates.
I am using Ubuntu 22.04. All my packages are up-to-date.
Manually downloading the index file e.g. using wget works fine and does not lead to any certificate problems.

```
266.023 C Failed  "https://meta.multimc.org/v1/net.minecraft/index.json"  with reason  6
  266.024 D Download failed in previous step: "https://meta.multimc.org/v1/net.minecraft/index.json"
  266.024 D Downloading  "https://meta.multimc.org/v1/net.minecraft/index.json"
  266.070 W QSslSocket: cannot call unresolved function SSL_get1_peer_certificate
  266.071 W QSslSocket: cannot call unresolved function SSL_get1_peer_certificate
  266.071 C Download "https://meta.multimc.org/v1/net.minecraft/index.json" SSL Error # 1  :  "The peer did not present any certificate"
  266.071 C Certificate in question:
 ""
  266.071 C Download "https://meta.multimc.org/v1/net.minecraft/index.json" SSL Error # 2  :  "The issuer certificate of a locally looked up certificate could not be found"
  266.071 C Certificate in question:
 "Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            0a:37:87:64:5e:5f:b4:8c:22:4e:fd:1b:ed:14:0c:3c
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=IE, O=Baltimore, OU=CyberTrust, CN=Baltimore CyberTrust Root
        Validity
            Not Before: Jan 27 12:48:08 2020 GMT
            Not After : Dec 31 23:59:59 2024 GMT
        Subject: C=US, O=Cloudflare, Inc., CN=Cloudflare Inc ECC CA-3
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:b9:ad:4d:66:99:14:0b:46:ec:1f:81:d1:2a:50:
                    1e:9d:03:15:2f:34:12:7d:2d:96:b8:88:38:9b:85:
                    5f:8f:bf:bb:4d:ef:61:46:c4:c9:73:d4:24:4f:e0:
                    ee:1c:ce:6c:b3:51:71:2f:6a:ee:4c:05:09:77:d3:
                    72:62:a4:9b:d7
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                A5:CE:37:EA:EB:B0:75:0E:94:67:88:B4:45:FA:D9:24:10:87:96:1F
            X509v3 Authority Key Identifier: 
                keyid:E5:9D:59:30:82:47:58:CC:AC:FA:08:54:36:86:7B:3A:B5:04:4D:F0

            X509v3 Key Usage: critical
                Digital Signature, Certificate Sign, CRL Sign
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:TRUE, pathlen:0
            Authority Information Access: 
                OCSP - URI:http://ocsp.digicert.com

            X509v3 CRL Distribution Points: 

                Full Name:
                  URI:http://crl3.digicert.com/Omniroot2025.crl

            X509v3 Certificate Policies: 
                Policy: 2.16.840.1.114412.1.1
                  CPS: https://www.digicert.com/CPS
                Policy: 2.16.840.1.114412.1.2
                Policy: 2.23.140.1.2.1
                Policy: 2.23.140.1.2.2
                Policy: 2.23.140.1.2.3

    Signature Algorithm: sha256WithRSAEncryption
         05:24:1d:dd:1b:b0:2a:eb:98:d6:85:e3:39:4d:5e:6b:57:9d:
         82:57:fc:eb:e8:31:a2:57:90:65:05:be:16:44:38:5a:77:02:
         b9:cf:10:42:c6:e1:92:a4:e3:45:27:f8:00:47:2c:68:a8:56:
         99:53:54:8f:ad:9e:40:c1:d0:0f:b6:d7:0d:0b:38:48:6c:50:
         2c:49:90:06:5b:64:1d:8b:cc:48:30:2e:de:08:e2:9b:49:22:
         c0:92:0c:11:5e:96:92:94:d5:fc:20:dc:56:6c:e5:92:93:bf:
         7a:1c:c0:37:e3:85:49:15:fa:2b:e1:74:39:18:0f:b7:da:f3:
         a2:57:58:60:4f:cc:8e:94:00:fc:46:7b:34:31:3e:4d:47:82:
         81:3a:cb:f4:89:5d:0e:ef:4d:0d:6e:9c:1b:82:24:dd:32:25:
         5d:11:78:51:10:3d:a0:35:23:04:2f:65:6f:9c:c1:d1:43:d7:
         d0:1e:f3:31:67:59:27:dd:6b:d2:75:09:93:11:24:24:14:cf:
         29:be:e6:23:c3:b8:8f:72:3f:e9:07:c8:24:44:53:7a:b3:b9:
         61:65:a1:4c:0e:c6:48:00:c9:75:63:05:87:70:45:52:83:d3:
         95:9d:45:ea:f0:e8:31:1d:7e:09:1f:0a:fe:3e:dd:aa:3c:5e:
         74:d2:ac:b1
"
  266.072 C Failed  "https://meta.multimc.org/v1/net.minecraft/index.json"  with reason  6
  266.072 D Download failed in previous step: "https://meta.multimc.org/v1/net.minecraft/index.json"
  266.072 C Task "NetJob(Download of meta file net.minecraft/index.json)" failed:  "Job 'Download of meta file net.minecraft/index.json' failed to process:
https://meta.multimc.org/v1/net.minecraft/index.json"
```

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment] 2022-10-30 14:46
please try installing `libssl-dev` and then trying again

**Comment by markuspi** [comment] 2022-10-30 15:52
@phit `libssl-dev 3.0.2-0ubuntu1.6 amd64` was already installed

**Comment by phit** [comment] 2022-10-31 15:01
mh so im not sure whats the proper way to solve this, multimc as far as i know needs [openssl 1.1.X](https://packages.ubuntu.com/search?keywords=libssl1.1) but that package is no longer officially available for ubuntu 22

google seems to suggest you can install the package from 21 http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1l-1ubuntu1.6_amd64.deb

**Comment by phit** [comment] 2023-02-24 19:02
this is caused by a broken qt install on the OS, if you need help resolving it join our discord for chat support

**Closed by phit** 2023-02-24 19:02 UTC
Labels: bug, system: Linux, packaging
