### ISSUE TITLE
Add keep account logged in as an option

### ISSUE THREAD

**Issue by JohnSmit268** [MultiMC/Launcher#4292] opened 2021-12-01 08:17 UTC
### Role

Playing modded minecraft

### Suggestion

Add keep account logged in as an option

### Benefit

It removes the need of account relogin upon every minecraft instance relaunch

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Please add an option to allow account login and api key caching to prevent redundant logins upon every instance launch.
As tested with official minecraft launcher this is possible.

**Comment by phit** [comment] 2021-12-01 08:57
update to the development version and duplicate of https://github.com/MultiMC/Launcher/issues/4071

![grafik](https://user-images.githubusercontent.com/2097483/144202955-33387332-4739-4e02-9d3d-0a345535fc3c.png)

**Comment by JohnSmit268** [comment] 2021-12-01 09:19
> update to the development version and duplicate of #4071
> 
> ![grafik](https://user-images.githubusercontent.com/2097483/144202955-33387332-4739-4e02-9d3d-0a345535fc3c.png)

![image](https://user-images.githubusercontent.com/16625616/144206141-c2e47d5f-1971-4ec2-9525-f051d6970299.png)
 As you can see I am already on developement update channel.
And this is not a bug report, but a mere suggestion

![image](https://user-images.githubusercontent.com/16625616/144206255-10790c25-d05a-4a4a-a7ef-7af67493a428.png)

![image](https://user-images.githubusercontent.com/16625616/144206393-323f86c6-e933-4f39-917e-59843ccbc23b.png)
On every instance launch multimc will log into microsoft account, as seen in the pictures.
The suggestion is to cache the api keys aquired and prevent redundant logins unless the keys are expired.

**Comment by JohnSmit268** [comment] 2021-12-01 09:20
I hope this suggestion gets reopened

**Comment by phit** [comment] 2021-12-01 09:44
oh that, yeah that's already being worked on to make the refresh run as a task in the background as needed instead of all the time

**Comment by JohnSmit268** [comment] 2021-12-01 09:49
thank you, that would be an amazing addition!

**Comment by phit** [comment] 2021-12-04 10:27
this was now added in the latest development version, if there's any issues with it let me know and make sure to provide your logs

**Closed by phit** 2021-12-04 10:27 UTC
Labels: Auth
