### ISSUE TITLE
[Suggestion] Modpack update notification

### ISSUE THREAD

**Issue by Srdjan-V** [MultiMC/Launcher#4580] opened 2022-03-14 15:51 UTC
### Role

I play modded minecraft.

### Suggestion

A simple notification that there is a new version of a modpack.

### Benefit

Its a QOL feature.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

To clarify i don't want it to update the modpack automatically, just to notify me that there is a new version.

This can be made to work only on one instance of one type of modpack.

**Comment by Janrupf** [comment] 2022-05-16 00:44
Duplicate of #2640

**Closed** 2022-05-16 07:33 UTC
Labels: suggestion
