### ISSUE TITLE
Support download from MCBBS source

### ISSUE THREAD

**Issue by mike-brown8** [MultiMC/Launcher#5039] opened 2023-01-12 06:23 UTC
### Role

I use the launcher to play Minecraft with mods and make modpacks.

### Suggestion

Support download from MCBBS source(library and other files, such as forge, optifine...).

### Benefit

In China, it's quite slow to download from Mojang and sometimes I can even not able to connect to Mojang file server.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Though we Chinese player have Netease version of Minecraft. However, it even force us to pay for mods and resourcepacks that are open-source and free to play. And it has a lot of BUGs that the origin version doesn't have, so I play this version of Minecraft instead of the Netease one.

**Comment by mike-brown8** [comment] 2023-01-12 06:26
Benefit: Attact more Chinese players and help players in China download game files easlier.

**Comment by mike-brown8** [comment] 2023-01-12 06:30
Oh, I forgot to leave a link. Here is the link of the source: download.mcbbs.net

**Comment by phit** [comment] 2023-01-12 08:03
Duplicate of https://github.com/MultiMC/Launcher/issues/2246, https://github.com/MultiMC/Launcher/issues/1311, etc

**Closed as completed by phit** 2023-01-12 08:03 UTC
Labels: close:duplicate, suggestion
