### ISSUE TITLE
Can't get logged to the launcher due to a "Gateway Time-out"

### ISSUE THREAD

**Issue by aboothered** [MultiMC/Launcher#4583] opened 2022-03-16 13:42 UTC
### Operating System

Windows

### Description of bug

Today Minecraft wasn't launching, so I tried logging off the launcher and back on to solve the issue but it worsened. It starts all fine and seemingly okay, but then it gets stuck in this step:

![image](https://user-images.githubusercontent.com/68480700/158602168-82734ba2-8e3b-4e5f-8846-a9d3eaffb820.png)

After a tad of that, the process suddenly stops and this error message shows up:

![image](https://user-images.githubusercontent.com/68480700/158602393-bbe757a3-f10c-4db8-bc3f-3965048c0449.png)

Guess it's a generalized problem, as a really similar yet not identical issue has been posted minutes ago. Felt like it was different enough to not be considered a duplicate.

### Steps to reproduce

I suppose just trying to log in MultiMC will provide this same result, if not then I've got no clue why it is happening to me, as yesterday it was working perfectly.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment] 2022-03-16 13:47
Duplicate of https://github.com/MultiMC/Launcher/issues/4582

**Closed by phit** 2022-03-16 13:47 UTC
Labels: bug
