### ISSUE TITLE
My account as disapered of my multimc

### ISSUE THREAD

**Issue by SaumonLord** [MultiMC/Launcher#5453] opened 2024-07-02 12:13 UTC
### Description of bug

Multimc tolds me that i don't have any account (BUT I HAVE AN ACCOUNT !)

### Steps to reproduce

I opened up multimc
It didn't show me accounts

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Problemreported** [comment] 2024-07-02 18:55
I think I have the same bug, so ill attempt to explain it in greater detail.
In my case, my account has expired and I need to re-connect it. I do so using the sign in with Microsoft option. Everything is doing well until it was attempting to connect to the Xbox services, in which I got this error
![image](https://github.com/MultiMC/Launcher/assets/115743004/981e2e36-0394-4ec6-b5e8-7c16c058ebdc)

I suspect its some update with an Api or something to do with Xbox.

_I don't work on Multimc just trying to help_

**Comment by NewCeptionDev** [comment] 2024-07-02 19:03
It appears that Xbox Live has issues, so this seems to be more of an Xbox Issue and not directly connected to MultiMC

**Comment by Calciferation** [comment] 2024-07-02 19:03
This issue does seem linked to the fact that Microsoft/Xbox's login servers are unavailable. The issue raised here is that MultiMC seems to delete account info after a failed connection, though.

**Comment by happysmash27** [comment] 2024-07-02 19:34
Is there any documentation for how accounts.json works? I wonder if it might be possible to re-create the needed info from the log file and then log in as offline mode.

**Comment by Kenzo-911** [comment] 2024-07-02 19:37
i get the same error.

**Comment by Hanekihyouka** [comment] 2024-07-02 19:50
same error with 

> Failed to authorization for xbox services. Error %2.

**Comment by chandrabe** [comment] 2024-07-02 19:56
Xbox Profile service is down currently ... this probably explain the issue

![image](https://github.com/MultiMC/Launcher/assets/1850080/b0ca66c4-8e35-4cd4-846e-93ecbf1fd073)

Status Page: 
https://support.xbox.com/en-US/xbox-live-status

**Comment by phit** [comment] 2024-07-02 20:00
https://twitter.com/mojangstatus/status/1800101837304987819
https://bugs.mojang.com/browse/WEB-7179

**Comment by happysmash27** [comment] 2024-07-02 20:01
I really shouldn't be spending time on something that's just going to get way easier as soon as the servers go back up (because then I can just make sure to keep a backup of the current file), but…

By finding a very, very old backup of MultiMC, looking at the accounts.json there (which was still on version 2), and grepping for some of the keys in the source code, I was able to determine that the relevant structure for accounts.json, both version 2 and 3, should in theory be able to be deduced from https://github.com/MultiMC/Launcher/blob/develop/launcher/minecraft/auth/AccountData.cpp.

**Comment by happysmash27** [comment] 2024-07-02 20:03
> Xbox Profile service is down currently ... this probably explain the issue
> 
> ![image](https://private-user-images.githubusercontent.com/1850080/345183189-b0ca66c4-8e35-4cd4-846e-93ecbf1fd073.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NTA1OTAsIm5iZiI6MTcxOTk1MDI5MCwicGF0aCI6Ii8xODUwMDgwLzM0NTE4MzE4OS1iMGNhNjZjNC04ZTM1LTRjZDQtODQ2ZS05M2VjYmYxZmQwNzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDJUMTk1ODEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWJiZjBkYTQyZjQxYmNkYzMxZGM4NTA2ZjE0YTY0N2E0ZmU2ZDY0MTY0MDAxZjYyYThlNGM4NWNkODNlN2M1NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iEojzuqlp5pEVYzbn_SCY6oiNBMansRWMkPsrwoF798)
> 
> Status Page: https://support.xbox.com/en-US/xbox-live-status

Good to know the status page is finally working! Before it was showing it was online when it was not.
![2024-07-02-115657_2560x2854_scrot](https://github.com/MultiMC/Launcher/assets/3620657/9a45ac93-00a4-4786-a3b1-35255c3d382a)

Now I can rest easy knowing I can just look at that page like I wanted to instead of constantly refreshing in MultiMC itself.

**Comment by happysmash27** [comment] 2024-07-02 20:13
I wonder if I can just replace the file with my absurdly old accounts.json from 2016 or so and have it work…

Sort of.
![2024-07-02-130937_802x623_scrot](https://github.com/MultiMC/Launcher/assets/3620657/6dbdc1b2-28b3-4905-a735-100329ee4d91)

But then it runs into #5391.
![2024-07-02-131004_339x141_scrot](https://github.com/MultiMC/Launcher/assets/3620657/90df1017-5c08-4043-88f6-691b53eb88a5)

**Comment by benhovinga** [comment] 2024-07-02 20:47
I also got the same error message. 

> Failed to authorization for xbox services. Error %2.

The %2 in the error message is annoying. Wasn't much help for an error.

**Comment by JoelTroch** [comment] 2024-07-02 20:58
@benhovinga Xbox Live authentication servers are currently unavailable due to an outage (this concerns Minecraft and Xbox Live as a whole, this is not specific to MultiMC), please consult the following links for more information and updates:

- https://support.xbox.com/en-US/xbox-live-status
- https://twitter.com/mojangstatus/status/1800101837304987819
- https://bugs.mojang.com/browse/WEB-7179

**Comment by JoelTroch** [comment] 2024-07-02 21:03
Furthermore, the issue was opened **before** the servers went down and I think it refers to the fact that the Microsoft account gets removed from MultiMC's list when an expired account cannot be refreshed (as mentioned by @Calciferation here: https://github.com/MultiMC/Launcher/issues/5453#issuecomment-2204092002)

Looking at the code's history, this behavior seems to have been added when #4998 has been merged. Judging from how the PR is worded, this seems to be an "intended behavior" (unless a MultiMC maintainer step in to say it's a bug).

**Comment by happysmash27** [comment] 2024-07-02 21:04
> I also got the same error message.
> 
> > Failed to authorization for xbox services. Error %2.
> 
> The %2 in the error message is annoying. Wasn't much help for an error.

The error message in the log (`MultiMC-0.log`) is a lot better and more useful:
```
156323.336 D AuthFlow: "Getting authorization to access Xbox services."
156323.336 D Getting authorization token for  "http://xboxlive.com"
156325.960 W AuthRequest::onRequestError: Error 403
156325.960 W AuthRequest::onRequestError: Error string:  "Error transferring https://xsts.auth.xboxlive.com/xsts/authorize - server replied: Service Unavailable"
156325.960 W AuthRequest::onRequestError: HTTP status 503 "Service Unavailable"
156325.960 W Reply error: 403
156325.960 C Task "MSASilent(0x240d240)" failed:  "Failed to get authorization for

                                                                                                                                      Xbox services. Error %2."
```

**Comment by benhovinga** [comment] 2024-07-02 21:11
@JoelTroch I am just curious if the %2 configuration for that specific error message was in MultiMC or if it was from the API callback.

**Comment by JoelTroch** [comment] 2024-07-02 21:12
> @JoelTroch I am just curious if the %2 configuration for that specific error message was in MultiMC or if it was from the API callback.

@happysmash27 just answered that question for you here: https://github.com/MultiMC/Launcher/issues/5453#issuecomment-2204416809

**Comment by andreasdc** [comment] 2024-07-02 21:50
> Furthermore, the issue was opened **before** the servers went down and I think it refers to the fact that the Microsoft account gets removed from MultiMC's list when an expired account cannot be refreshed (as mentioned by @Calciferation here: [#5453 (comment)](https://github.com/MultiMC/Launcher/issues/5453#issuecomment-2204092002))
> 
> Looking at the code's history, this behavior seems to have been added when #4998 has been merged. Judging from how the PR is worded, this seems to be an "intended behavior" (unless a MultiMC maintainer step in to say it's a bug).

It should use cached data and refresh if needed, right?

**Comment by f-michaut** [comment] 2024-07-03 04:31
> Looking at the code's history, this behavior seems to have been added when https://github.com/MultiMC/Launcher/pull/4998 has been merged. Judging from how the PR is worded, this seems to be an "intended behavior" (unless a MultiMC maintainer step in to say it's a bug).

TBH I think it is not expected behavior by the user. If the login fails, the user will probably want to play right away, and not wait for Auth servers to come back up.
So the user will want to use Offline Mode which will be prevented by MultiMC if the account gets removed !
Happened to me a few weeks ago, had to boot up the regular minecraft launcher and copy over my Instance files to the original `.minecraft` in order to play.

I was effectively locked out of MultiMC and no way to add my account back cause auth servers where down.
I dont think MultiMC should delete accounts that are failing to connect for that reason. It seems to be quite common for Auth servers to be down theses days, and we should be able to rely on offline mode in theses situations (that's kind of the point of that feature)

**Comment by MousePak** [comment] 2024-07-03 08:51
https://github.com/MultiMC/Launcher/issues/5456 Closed in error imo

The message users receive gives no indication of what went wrong and should be improved 
Issue opened to suggest Failed to authorization for xbox services. Error %2. have more details added

While the logs within multimc show networking error on the microsoft side, this could be parsed into the user error deplayed on screen. This would greatly improve usability to users while reducing errors logged for a microsoft issue

**Comment by ShadowClawmc** [comment] 2024-07-04 16:49
Instead of getting the Error %2 i get  an error saying that the microsoft user authentification has failed is there a way to fix that

**Comment by garath77** [comment] 2024-07-05 20:48
I've been trying to get 2 accounts authenticated on 2 different computers for a couple of days now, AFTER the Xbox servers came back up. Both accounts are brand new. Strangely enough, some other accounts seem to work, but some don't. Any idea what could be causing that?

**Comment by phit** [comment] 2024-07-05 20:49
make sure you are using a password to login instead of email code, you can set a account password at https://account.live.com/proofs/manage/additional

**Closed as completed** 2024-07-17 13:37 UTC
Labels: external, Auth

**Comment by andreasdc** [comment] 2024-07-17 14:25
> make sure you are using a password to login instead of email code, you can set a account password at https://account.live.com/proofs/manage/additional

How does that solve the issue?

**Comment by phit** [comment] 2024-07-17 16:02
never claimed it did, that reply was to one of the countless offtopic comments in here, the actual issue of accounts being removed if login failed was added with https://github.com/MultiMC/Launcher/pull/4998 and is intentional, before you had to manually remove the account each time the login expired which was even worse..

the bug here is that accounts are being removed if the refresh failed due to other issues than actually expiring, but that is already being tracked by https://github.com/MultiMC/Launcher/issues/5078

auth in multimc is in a sad state in general, with basically anything other than the most basic use case failing in some way https://github.com/MultiMC/Launcher/labels/Auth
