### ISSUE TITLE
Auto-refresh MSA Account Token on Instance Start

### ISSUE THREAD

**Issue by DerMistkaefer** [MultiMC/Launcher#5479] opened 2024-07-25 16:07 UTC
### Role

I play Minecraft

### Suggestion

Implement a feature where MultiMC automatically refreshes the token of the selected MSA (Microsoft Account) account when starting an instance if the error message about choosing an offline account name appears.

### Benefit

This feature would eliminate the need for users to manually go into the menu to update the token each time, providing a smoother and more seamless experience when starting instances.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment] 2024-07-25 16:21
Duplicate of https://github.com/MultiMC/Launcher/issues/4355

**Closed as completed by phit** 2024-07-25 16:21 UTC
Labels: close:duplicate, Auth
