### ISSUE TITLE
Cannot compile, error: identifier ‘requires’ is a keyword in C++20

### ISSUE THREAD

**Issue by uuigdevt47** [MultiMC/Launcher#5211] opened 2023-07-07 22:24 UTC
### Operating System
Linux

### Description of bug
Cannot compile:
```
...
src/Launcher/launcher/minecraft/VersionFile.h:97:22: error: identifier ‘requires’ is a keyword in C++20 [-Werror=c++20-compat]
   97 |     Meta::RequireSet requires;
      |                      ^~~~~~~~
cc1plus: all warnings being treated as errors
 ...
```
 
 ### Important flags
```
CFLAGS="-march=native -mtune=native -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
LTOFLAGS="-flto=auto"
MAKEFLAGS="-j128"
```

### GCC version
GCC 13.1.1

### Steps to reproduce
`make -j$(nproc --all)`

### This issue is unique
- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by monstro1** [comment] 2023-07-25 21:56
Also having this issue.

Tried to build/compile via the AUR on Manjaro Linux

**Comment by ChrisJStone** [comment] 2023-07-25 23:25
Same issue of Fedora 38.

**Comment by ChrisJStone** [comment] 2023-07-26 03:30
The root cause of the issue is cmake will use any flags present in CMAKE_CXX_FLAGS as default flags for all build types. I've submitted a PR that works around this by moving -Werror which is the flag that is causing this issue to CMAKE_CXX_FLAGS_DEBUG. If this flag needs to be enabled adding -DCMAKE_BUILD_TYPE=Debug to the cmake cmd will enable it.

**Comment by arthomnix** [comment] 2023-07-26 10:14
This can be fixed by adding `-Wno-c++20-compat` to your CMAKE_CXX_FLAGS (in CMakeLists.txt)

**Comment by ChrisJStone** [comment] 2023-07-26 21:35
Thank you for the information. I'll get that changed and update my PR

**Closed as completed** 2024-01-31 23:36 UTC
Labels: bug
