### ISSUE TITLE
As of most recent update, fails to get and run forge installers

### ISSUE THREAD

**Issue by LeakingAmps** [MultiMC/Launcher#5354] opened 2024-02-28 20:16 UTC
### Operating System

Windows

### Description of bug

When launching a new pack, I receive the error 

`Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance test2' failed to process:
https://maven.minecraftforge.net/net/minecraftforge/forge/1.20.4-49.0.30/forge-1.20.4-49.0.30-installer.jar`

Manually navigating to this URL lets me download the jar just fine, so I suspect it's an issue with MultiMC.

This issue did not appear to be present in the last version, and occurs even on a fresh install of MultiMC

I've found similar reports in the bug tracker, but all were quite old, and closed.

### Steps to reproduce

Make a new instance
(Optionally, launch instance to install it)
Edit Instance
Add Forge
Launch instance

*fails to install forge*

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by LeakingAmps** [comment] 2024-02-28 20:17
I have been trying to figure out how to manually install forge for MultiMC versions, but it looks like it's trickier than I expected

**Comment by return0927** [comment] 2024-02-28 20:31
As I mentioned in https://github.com/MultiMC/Launcher/issues/5353, this seems to be caused with hash validation failure

**Comment by phit** [comment] 2024-02-28 23:17
Duplicate of https://github.com/MultiMC/Launcher/issues/5353

**Closed as completed by phit** 2024-02-28 23:17 UTC
Labels: bug
