### ISSUE TITLE
[Suggestion] Automatic Java Version decision based on the MC Version

### ISSUE THREAD

**Issue by timfischbach** [MultiMC/Launcher#4310] opened 2021-12-06 09:58 UTC
### Role

I play Modded and latest MC and since 1.7.10 runs only in 1.8.0 Java and 1.17.1 only in Java 16, it would be nice to have such a feature. Currently, I always need to go to the settings and switch it manually

### Suggestion

In Java settings, there should be an automatic version switch feature. If MC Version < [User Input MC Version] use [User Input Java Version] else use [User input Java Version]

### Benefit

I recently play modded and latest b2b, and it's always annoying to switch Java versions manually in the settings.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment] 2021-12-06 10:12
Duplicate of https://github.com/MultiMC/Launcher/issues/4013
it's on the roadmap

**Closed by phit** 2021-12-06 10:12 UTC
