### ISSUE TITLE
allow importation of curseforge modpacks from its new dedicated launcher.

### ISSUE THREAD

**Issue by QTpyeRose** [MultiMC/Launcher#5149] opened 2023-05-07 09:11 UTC
### Role

ease of modpack instalation

### Suggestion

add support for import from the curseforge launcher

### Benefit

so i can stop using ftb overwolf.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

so fairly recently curse-forge released a standalone launcher for cruse-forge.

https://download.curseforge.com/

while there is already import from the FTB app modpack option, the FTB app runs on over-wolf and is practically bloatware (in my opinion)

the new launcher seems to be less bloatware-y

support for importing mod-packs from it to multi MC would be a nice thing to have.

although i can see if its to much work, or if its un-needed due to being able to get the mod-packs though the FTB app

**Comment by phit** [comment] 2023-05-08 14:17
Duplicate of https://github.com/MultiMC/Launcher/issues/4851

**Closed as completed by phit** 2023-05-08 14:17 UTC
Labels: close:duplicate, suggestion
