### ISSUE TITLE
I hope that can support custom download source link

### ISSUE THREAD

**Issue by SheepYhangCN** [MultiMC/Launcher#4870] opened 2022-08-06 15:24 UTC
### Role

Creating a instance and start it

### Suggestion

Add a feature that can allow players to set download source link by themselves

### Benefit

The speed of downloading files from mojang server is too slow in China mainland

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

so, i know there are many suggestion to you to added bmclapi
but, i am not here to suggestion to do this, because it is only for Chinese players
instead, i hope you can add a feature to allow players to set download source link by themselves
it can redirect every download link to another
(for example, it can allows to change "https://launchermeta.mojang.com" to "https://bmclapi2.bangbang93.com", "https://meta.fabricmc.net" to "https://bmclapi2.bangbang93.com/fabric-meta", etc)
just add a way for players to custom, and they can also make a mirror download by themselves

**Comment by phit** [comment] 2022-08-06 17:29
Duplicate of https://github.com/MultiMC/Launcher/issues/2246

**Closed by phit** 2022-08-06 17:29 UTC
