### ISSUE TITLE
MultiMC crash when "scanning" a file

### ISSUE THREAD

**Issue by Starmania** [MultiMC/Launcher#4361] opened 2021-12-16 14:20 UTC
### Operating System

Windows

### Description of bug

When you try to edit an instance, MultiMC will crash if a specific file is in this instance.

[The log file 2021-12-09-1.log.gz](https://github.com/MultiMC/Launcher/files/7727945/2021-12-09-1.log.gz)

Video to reproduce this bug will be added in few minutes
PS: sorry for my English, I'm French

### Steps to reproduce

* Put the log file in anywhere the .minecraft
* Try editing instance
* MultiMC will freeze and crash without any info

### Suspected cause

* MultiMC seemes to scann the full .minecraft and try to decompress the file, after IDK, surely the size when it is not compressed

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Starmania** [comment] 2021-12-16 14:28
[The video](https://drive.google.com/file/d/1X59PfEcqp9FEO7lfIwrU_4OjG6uE7Mys/view?usp=sharing)

**Comment by spannerman79** [comment] 2021-12-16 14:59
https://github.com/MultiMC/Launcher/wiki/Minecraft-Logs

When you provide logs, as stated, **Use the upload log button**

Secondly, You should of used Youtube to upload that video.  Would have been much simpler.

Third, That error;
```
[14:49:46] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error'
```
That is **not** a MultiMC issue.  That is your GPU.  Either being too old, drivers needing to be installed _correctly_ or it (your GPU) is FUBAR.

**Comment by phit** [comment] 2021-12-16 15:42
their ticket isnt even about Minecraft @spannerman79, they say MultiMC is crashing when that log file is in an instance, which sounds a lot like https://github.com/MultiMC/Launcher/issues/4228

**Comment by phit** [comment] 2021-12-16 15:44
Yep, just watched the video, duplicate of #4228

**Closed by phit** 2021-12-16 15:44 UTC
Labels: bug

**Comment by spannerman79** [comment] 2021-12-17 11:09
> their ticket isnt even about Minecraft

And yet avoiding/ignoring the _actual_ issue is basically putting lipstick on a pig @phit
